//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include "./tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

UsdVrmTokensType::UsdVrmTokensType()
    : _1_0("1.0", TfToken::Immortal),
      inputsVrmMaterialAlphaCutoff("inputs:vrm:material:alphaCutoff", TfToken::Immortal),
      inputsVrmMaterialAlphaMode("inputs:vrm:material:alphaMode", TfToken::Immortal),
      inputsVrmMaterialBaseColorAlphaFactor("inputs:vrm:material:baseColorAlphaFactor",
                                            TfToken::Immortal),
      inputsVrmMaterialBaseColorFactor("inputs:vrm:material:baseColorFactor", TfToken::Immortal),
      inputsVrmMaterialDoubleSided("inputs:vrm:material:doubleSided", TfToken::Immortal),
      inputsVrmMaterialEmissiveFactor("inputs:vrm:material:emissiveFactor", TfToken::Immortal),
      inputsVrmMaterialEmissiveStrength("inputs:vrm:material:emissiveStrength", TfToken::Immortal),
      inputsVrmMaterialMetallicFactor("inputs:vrm:material:metallicFactor", TfToken::Immortal),
      inputsVrmMaterialRoughnessFactor("inputs:vrm:material:roughnessFactor", TfToken::Immortal),
      inputsVrmMaterialUnlit("inputs:vrm:material:unlit", TfToken::Immortal),
      inputsVrmMtoonGiEqualizationFactor("inputs:vrm:mtoon:giEqualizationFactor",
                                         TfToken::Immortal),
      inputsVrmMtoonMatcapFactor("inputs:vrm:mtoon:matcapFactor", TfToken::Immortal),
      inputsVrmMtoonOutlineColorFactor("inputs:vrm:mtoon:outlineColorFactor", TfToken::Immortal),
      inputsVrmMtoonOutlineLightingMixFactor("inputs:vrm:mtoon:outlineLightingMixFactor",
                                             TfToken::Immortal),
      inputsVrmMtoonOutlineWidthFactor("inputs:vrm:mtoon:outlineWidthFactor", TfToken::Immortal),
      inputsVrmMtoonOutlineWidthMode("inputs:vrm:mtoon:outlineWidthMode", TfToken::Immortal),
      inputsVrmMtoonParametricRimColorFactor("inputs:vrm:mtoon:parametricRimColorFactor",
                                             TfToken::Immortal),
      inputsVrmMtoonParametricRimFresnelPowerFactor(
          "inputs:vrm:mtoon:parametricRimFresnelPowerFactor", TfToken::Immortal),
      inputsVrmMtoonParametricRimLiftFactor("inputs:vrm:mtoon:parametricRimLiftFactor",
                                            TfToken::Immortal),
      inputsVrmMtoonRenderQueueOffsetNumber("inputs:vrm:mtoon:renderQueueOffsetNumber",
                                            TfToken::Immortal),
      inputsVrmMtoonRimLightingMixFactor("inputs:vrm:mtoon:rimLightingMixFactor",
                                         TfToken::Immortal),
      inputsVrmMtoonShadeColorFactor("inputs:vrm:mtoon:shadeColorFactor", TfToken::Immortal),
      inputsVrmMtoonShadingShiftFactor("inputs:vrm:mtoon:shadingShiftFactor", TfToken::Immortal),
      inputsVrmMtoonShadingToonyFactor("inputs:vrm:mtoon:shadingToonyFactor", TfToken::Immortal),
      inputsVrmMtoonSpecVersion("inputs:vrm:mtoon:specVersion", TfToken::Immortal),
      inputsVrmMtoonTransparentWithZWrite("inputs:vrm:mtoon:transparentWithZWrite",
                                          TfToken::Immortal),
      inputsVrmMtoonUvAnimationRotationSpeedFactor(
          "inputs:vrm:mtoon:uvAnimationRotationSpeedFactor", TfToken::Immortal),
      inputsVrmMtoonUvAnimationScrollXSpeedFactor("inputs:vrm:mtoon:uvAnimationScrollXSpeedFactor",
                                                  TfToken::Immortal),
      inputsVrmMtoonUvAnimationScrollYSpeedFactor("inputs:vrm:mtoon:uvAnimationScrollYSpeedFactor",
                                                  TfToken::Immortal),
      inputsVrmTextureInfo("inputs:vrm:textureInfo", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_File(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:file", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_Scale(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:scale", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_Strength(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:strength", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_TexCoord(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:texCoord", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_TransformOffset(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:transform:offset", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_TransformRotation(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:transform:rotation", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_TransformScale(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:transform:scale", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_WrapS(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:wrapS", TfToken::Immortal),
      inputsVrmTextureInfo_MultipleApplyTemplate_WrapT(
          "inputs:vrm:textureInfo:__INSTANCE_NAME__:wrapT", TfToken::Immortal),
      none("none", TfToken::Immortal), repeat("repeat", TfToken::Immortal),
      vrmAxis("vrm:axis", TfToken::Immortal), vrmCenter("vrm:center", TfToken::Immortal),
      vrmColliderGroups("vrm:colliderGroups", TfToken::Immortal),
      vrmConstrained("vrm:constrained", TfToken::Immortal),
      vrmDragForce("vrm:dragForce", TfToken::Immortal),
      vrmExpressionName("vrm:expressionName", TfToken::Immortal),
      vrmExpressionType("vrm:expressionType", TfToken::Immortal),
      vrmGravityDir("vrm:gravityDir", TfToken::Immortal),
      vrmGravityPower("vrm:gravityPower", TfToken::Immortal),
      vrmHitRadius("vrm:hitRadius", TfToken::Immortal),
      vrmHumanBonesChest("vrm:humanBones:chest", TfToken::Immortal),
      vrmHumanBonesHead("vrm:humanBones:head", TfToken::Immortal),
      vrmHumanBonesHips("vrm:humanBones:hips", TfToken::Immortal),
      vrmHumanBonesJaw("vrm:humanBones:jaw", TfToken::Immortal),
      vrmHumanBonesLeftEye("vrm:humanBones:leftEye", TfToken::Immortal),
      vrmHumanBonesLeftFoot("vrm:humanBones:leftFoot", TfToken::Immortal),
      vrmHumanBonesLeftHand("vrm:humanBones:leftHand", TfToken::Immortal),
      vrmHumanBonesLeftIndexDistal("vrm:humanBones:leftIndexDistal", TfToken::Immortal),
      vrmHumanBonesLeftIndexIntermediate("vrm:humanBones:leftIndexIntermediate", TfToken::Immortal),
      vrmHumanBonesLeftIndexProximal("vrm:humanBones:leftIndexProximal", TfToken::Immortal),
      vrmHumanBonesLeftLittleDistal("vrm:humanBones:leftLittleDistal", TfToken::Immortal),
      vrmHumanBonesLeftLittleIntermediate("vrm:humanBones:leftLittleIntermediate",
                                          TfToken::Immortal),
      vrmHumanBonesLeftLittleProximal("vrm:humanBones:leftLittleProximal", TfToken::Immortal),
      vrmHumanBonesLeftLowerArm("vrm:humanBones:leftLowerArm", TfToken::Immortal),
      vrmHumanBonesLeftLowerLeg("vrm:humanBones:leftLowerLeg", TfToken::Immortal),
      vrmHumanBonesLeftMiddleDistal("vrm:humanBones:leftMiddleDistal", TfToken::Immortal),
      vrmHumanBonesLeftMiddleIntermediate("vrm:humanBones:leftMiddleIntermediate",
                                          TfToken::Immortal),
      vrmHumanBonesLeftMiddleProximal("vrm:humanBones:leftMiddleProximal", TfToken::Immortal),
      vrmHumanBonesLeftRingDistal("vrm:humanBones:leftRingDistal", TfToken::Immortal),
      vrmHumanBonesLeftRingIntermediate("vrm:humanBones:leftRingIntermediate", TfToken::Immortal),
      vrmHumanBonesLeftRingProximal("vrm:humanBones:leftRingProximal", TfToken::Immortal),
      vrmHumanBonesLeftShoulder("vrm:humanBones:leftShoulder", TfToken::Immortal),
      vrmHumanBonesLeftThumbDistal("vrm:humanBones:leftThumbDistal", TfToken::Immortal),
      vrmHumanBonesLeftThumbMetacarpal("vrm:humanBones:leftThumbMetacarpal", TfToken::Immortal),
      vrmHumanBonesLeftThumbProximal("vrm:humanBones:leftThumbProximal", TfToken::Immortal),
      vrmHumanBonesLeftToes("vrm:humanBones:leftToes", TfToken::Immortal),
      vrmHumanBonesLeftUpperArm("vrm:humanBones:leftUpperArm", TfToken::Immortal),
      vrmHumanBonesLeftUpperLeg("vrm:humanBones:leftUpperLeg", TfToken::Immortal),
      vrmHumanBonesNeck("vrm:humanBones:neck", TfToken::Immortal),
      vrmHumanBonesRightEye("vrm:humanBones:rightEye", TfToken::Immortal),
      vrmHumanBonesRightFoot("vrm:humanBones:rightFoot", TfToken::Immortal),
      vrmHumanBonesRightHand("vrm:humanBones:rightHand", TfToken::Immortal),
      vrmHumanBonesRightIndexDistal("vrm:humanBones:rightIndexDistal", TfToken::Immortal),
      vrmHumanBonesRightIndexIntermediate("vrm:humanBones:rightIndexIntermediate",
                                          TfToken::Immortal),
      vrmHumanBonesRightIndexProximal("vrm:humanBones:rightIndexProximal", TfToken::Immortal),
      vrmHumanBonesRightLittleDistal("vrm:humanBones:rightLittleDistal", TfToken::Immortal),
      vrmHumanBonesRightLittleIntermediate("vrm:humanBones:rightLittleIntermediate",
                                           TfToken::Immortal),
      vrmHumanBonesRightLittleProximal("vrm:humanBones:rightLittleProximal", TfToken::Immortal),
      vrmHumanBonesRightLowerArm("vrm:humanBones:rightLowerArm", TfToken::Immortal),
      vrmHumanBonesRightLowerLeg("vrm:humanBones:rightLowerLeg", TfToken::Immortal),
      vrmHumanBonesRightMiddleDistal("vrm:humanBones:rightMiddleDistal", TfToken::Immortal),
      vrmHumanBonesRightMiddleIntermediate("vrm:humanBones:rightMiddleIntermediate",
                                           TfToken::Immortal),
      vrmHumanBonesRightMiddleProximal("vrm:humanBones:rightMiddleProximal", TfToken::Immortal),
      vrmHumanBonesRightRingDistal("vrm:humanBones:rightRingDistal", TfToken::Immortal),
      vrmHumanBonesRightRingIntermediate("vrm:humanBones:rightRingIntermediate", TfToken::Immortal),
      vrmHumanBonesRightRingProximal("vrm:humanBones:rightRingProximal", TfToken::Immortal),
      vrmHumanBonesRightShoulder("vrm:humanBones:rightShoulder", TfToken::Immortal),
      vrmHumanBonesRightThumbDistal("vrm:humanBones:rightThumbDistal", TfToken::Immortal),
      vrmHumanBonesRightThumbMetacarpal("vrm:humanBones:rightThumbMetacarpal", TfToken::Immortal),
      vrmHumanBonesRightThumbProximal("vrm:humanBones:rightThumbProximal", TfToken::Immortal),
      vrmHumanBonesRightToes("vrm:humanBones:rightToes", TfToken::Immortal),
      vrmHumanBonesRightUpperArm("vrm:humanBones:rightUpperArm", TfToken::Immortal),
      vrmHumanBonesRightUpperLeg("vrm:humanBones:rightUpperLeg", TfToken::Immortal),
      vrmHumanBonesSpine("vrm:humanBones:spine", TfToken::Immortal),
      vrmHumanBonesUpperChest("vrm:humanBones:upperChest", TfToken::Immortal),
      vrmIsBinary("vrm:isBinary", TfToken::Immortal), vrmJoints("vrm:joints", TfToken::Immortal),
      vrmLeftEye("vrm:leftEye", TfToken::Immortal),
      vrmMaterialColorTargets("vrm:materialColorTargets", TfToken::Immortal),
      vrmMaterialColorTypes("vrm:materialColorTypes", TfToken::Immortal),
      vrmMaterialColorValues("vrm:materialColorValues", TfToken::Immortal),
      vrmMorphTargets("vrm:morphTargets", TfToken::Immortal),
      vrmMorphTargetWeights("vrm:morphTargetWeights", TfToken::Immortal),
      vrmNode("vrm:node", TfToken::Immortal), vrmOffset("vrm:offset", TfToken::Immortal),
      vrmOverrideBlink("vrm:overrideBlink", TfToken::Immortal),
      vrmOverrideLookAt("vrm:overrideLookAt", TfToken::Immortal),
      vrmOverrideMouth("vrm:overrideMouth", TfToken::Immortal),
      vrmRadius("vrm:radius", TfToken::Immortal), vrmRightEye("vrm:rightEye", TfToken::Immortal),
      vrmShape("vrm:shape", TfToken::Immortal), vrmSkeleton("vrm:skeleton", TfToken::Immortal),
      vrmSource("vrm:source", TfToken::Immortal), vrmStiffness("vrm:stiffness", TfToken::Immortal),
      vrmTail("vrm:tail", TfToken::Immortal), vrmType("vrm:type", TfToken::Immortal),
      vrmWeight("vrm:weight", TfToken::Immortal),
      VrmColliderAPI("VrmColliderAPI", TfToken::Immortal),
      VrmConstraintAPI("VrmConstraintAPI", TfToken::Immortal),
      VrmExpressionAPI("VrmExpressionAPI", TfToken::Immortal),
      VrmHumanoidAPI("VrmHumanoidAPI", TfToken::Immortal),
      VrmLookAtAPI("VrmLookAtAPI", TfToken::Immortal),
      VrmMaterialAPI("VrmMaterialAPI", TfToken::Immortal),
      VrmMToonAPI("VrmMToonAPI", TfToken::Immortal),
      VrmSpringBoneAPI("VrmSpringBoneAPI", TfToken::Immortal),
      VrmTextureInfoAPI("VrmTextureInfoAPI", TfToken::Immortal),
      allTokens({_1_0,
                 inputsVrmMaterialAlphaCutoff,
                 inputsVrmMaterialAlphaMode,
                 inputsVrmMaterialBaseColorAlphaFactor,
                 inputsVrmMaterialBaseColorFactor,
                 inputsVrmMaterialDoubleSided,
                 inputsVrmMaterialEmissiveFactor,
                 inputsVrmMaterialEmissiveStrength,
                 inputsVrmMaterialMetallicFactor,
                 inputsVrmMaterialRoughnessFactor,
                 inputsVrmMaterialUnlit,
                 inputsVrmMtoonGiEqualizationFactor,
                 inputsVrmMtoonMatcapFactor,
                 inputsVrmMtoonOutlineColorFactor,
                 inputsVrmMtoonOutlineLightingMixFactor,
                 inputsVrmMtoonOutlineWidthFactor,
                 inputsVrmMtoonOutlineWidthMode,
                 inputsVrmMtoonParametricRimColorFactor,
                 inputsVrmMtoonParametricRimFresnelPowerFactor,
                 inputsVrmMtoonParametricRimLiftFactor,
                 inputsVrmMtoonRenderQueueOffsetNumber,
                 inputsVrmMtoonRimLightingMixFactor,
                 inputsVrmMtoonShadeColorFactor,
                 inputsVrmMtoonShadingShiftFactor,
                 inputsVrmMtoonShadingToonyFactor,
                 inputsVrmMtoonSpecVersion,
                 inputsVrmMtoonTransparentWithZWrite,
                 inputsVrmMtoonUvAnimationRotationSpeedFactor,
                 inputsVrmMtoonUvAnimationScrollXSpeedFactor,
                 inputsVrmMtoonUvAnimationScrollYSpeedFactor,
                 inputsVrmTextureInfo,
                 inputsVrmTextureInfo_MultipleApplyTemplate_File,
                 inputsVrmTextureInfo_MultipleApplyTemplate_Scale,
                 inputsVrmTextureInfo_MultipleApplyTemplate_Strength,
                 inputsVrmTextureInfo_MultipleApplyTemplate_TexCoord,
                 inputsVrmTextureInfo_MultipleApplyTemplate_TransformOffset,
                 inputsVrmTextureInfo_MultipleApplyTemplate_TransformRotation,
                 inputsVrmTextureInfo_MultipleApplyTemplate_TransformScale,
                 inputsVrmTextureInfo_MultipleApplyTemplate_WrapS,
                 inputsVrmTextureInfo_MultipleApplyTemplate_WrapT,
                 none,
                 repeat,
                 vrmAxis,
                 vrmCenter,
                 vrmColliderGroups,
                 vrmConstrained,
                 vrmDragForce,
                 vrmExpressionName,
                 vrmExpressionType,
                 vrmGravityDir,
                 vrmGravityPower,
                 vrmHitRadius,
                 vrmHumanBonesChest,
                 vrmHumanBonesHead,
                 vrmHumanBonesHips,
                 vrmHumanBonesJaw,
                 vrmHumanBonesLeftEye,
                 vrmHumanBonesLeftFoot,
                 vrmHumanBonesLeftHand,
                 vrmHumanBonesLeftIndexDistal,
                 vrmHumanBonesLeftIndexIntermediate,
                 vrmHumanBonesLeftIndexProximal,
                 vrmHumanBonesLeftLittleDistal,
                 vrmHumanBonesLeftLittleIntermediate,
                 vrmHumanBonesLeftLittleProximal,
                 vrmHumanBonesLeftLowerArm,
                 vrmHumanBonesLeftLowerLeg,
                 vrmHumanBonesLeftMiddleDistal,
                 vrmHumanBonesLeftMiddleIntermediate,
                 vrmHumanBonesLeftMiddleProximal,
                 vrmHumanBonesLeftRingDistal,
                 vrmHumanBonesLeftRingIntermediate,
                 vrmHumanBonesLeftRingProximal,
                 vrmHumanBonesLeftShoulder,
                 vrmHumanBonesLeftThumbDistal,
                 vrmHumanBonesLeftThumbMetacarpal,
                 vrmHumanBonesLeftThumbProximal,
                 vrmHumanBonesLeftToes,
                 vrmHumanBonesLeftUpperArm,
                 vrmHumanBonesLeftUpperLeg,
                 vrmHumanBonesNeck,
                 vrmHumanBonesRightEye,
                 vrmHumanBonesRightFoot,
                 vrmHumanBonesRightHand,
                 vrmHumanBonesRightIndexDistal,
                 vrmHumanBonesRightIndexIntermediate,
                 vrmHumanBonesRightIndexProximal,
                 vrmHumanBonesRightLittleDistal,
                 vrmHumanBonesRightLittleIntermediate,
                 vrmHumanBonesRightLittleProximal,
                 vrmHumanBonesRightLowerArm,
                 vrmHumanBonesRightLowerLeg,
                 vrmHumanBonesRightMiddleDistal,
                 vrmHumanBonesRightMiddleIntermediate,
                 vrmHumanBonesRightMiddleProximal,
                 vrmHumanBonesRightRingDistal,
                 vrmHumanBonesRightRingIntermediate,
                 vrmHumanBonesRightRingProximal,
                 vrmHumanBonesRightShoulder,
                 vrmHumanBonesRightThumbDistal,
                 vrmHumanBonesRightThumbMetacarpal,
                 vrmHumanBonesRightThumbProximal,
                 vrmHumanBonesRightToes,
                 vrmHumanBonesRightUpperArm,
                 vrmHumanBonesRightUpperLeg,
                 vrmHumanBonesSpine,
                 vrmHumanBonesUpperChest,
                 vrmIsBinary,
                 vrmJoints,
                 vrmLeftEye,
                 vrmMaterialColorTargets,
                 vrmMaterialColorTypes,
                 vrmMaterialColorValues,
                 vrmMorphTargets,
                 vrmMorphTargetWeights,
                 vrmNode,
                 vrmOffset,
                 vrmOverrideBlink,
                 vrmOverrideLookAt,
                 vrmOverrideMouth,
                 vrmRadius,
                 vrmRightEye,
                 vrmShape,
                 vrmSkeleton,
                 vrmSource,
                 vrmStiffness,
                 vrmTail,
                 vrmType,
                 vrmWeight,
                 VrmColliderAPI,
                 VrmConstraintAPI,
                 VrmExpressionAPI,
                 VrmHumanoidAPI,
                 VrmLookAtAPI,
                 VrmMaterialAPI,
                 VrmMToonAPI,
                 VrmSpringBoneAPI,
                 VrmTextureInfoAPI})
{
}

TfStaticData<UsdVrmTokensType> UsdVrmTokens;

PXR_NAMESPACE_CLOSE_SCOPE
