# SPDX-License-Identifier: Apache-2.0
"""End-to-end smoke tests for the usdVrm file-format plugin.

Drives the freshly built plugin through OpenUSD's Python bindings: opens each
committed .vrm fixture as a stage and asserts the import contract. Fixtures are
generated by tools/generate_fixtures.py.

The build wires PXR_PLUGINPATH_NAME / PATH / PYTHONPATH (see CMakeLists.txt);
when run by hand, do it inside `ost plugin run plugins/usdVrmFileFormat -- python ...`.
"""
import os
import pathlib
import sys
import tempfile

from pxr import Ar, Gf, Plug, Sdf, Usd, UsdGeom, UsdShade, UsdSkel, Vt

FIXTURES = pathlib.Path(__file__).parent / "fixtures"
TOOLS = pathlib.Path(__file__).parents[1] / "tools"
sys.path.insert(0, str(TOOLS))

from package_vrm import _package_member_path, package_stage


def _open(name):
    stage = Usd.Stage.Open(str(FIXTURES / name))
    assert stage, f"failed to open {name}"
    return stage


def _vclose(a, b, eps=1e-5):
    return all(abs(a[i] - b[i]) < eps for i in range(len(a)))


def check_minimal():
    """Skinned mesh + non-skinned node-placed accessory; IBM bind; humanoid."""
    stage = _open("minimal.vrm")

    dp = stage.GetDefaultPrim()
    assert dp and dp.GetPath().pathString == "/Asset", dp
    assert dp.GetTypeName() == "SkelRoot", dp.GetTypeName()
    assert abs(UsdGeom.GetStageMetersPerUnit(stage) - 1.0) < 1e-9
    assert UsdGeom.GetStageUpAxis(stage) == UsdGeom.Tokens.y

    vrm = dp.GetCustomData().get("vrm", {})
    assert vrm.get("sourceFormat") == "VRM", vrm
    assert vrm.get("schemaContractVersion") == 1, vrm
    assert vrm.get("specVersion") == "1.0", vrm
    assert vrm.get("meta"), "VRM meta should be preserved on /Asset"
    assert vrm.get("rawExtension"), "VRM rawExtension should be preserved"
    assert "humanoid" in vrm["rawExtension"], "rawExtension should be the VRM block"
    # VRM 1.0 already faces +Z: no front-normalization rotation.
    assert vrm.get("sourceFrontAxis") == "+Z", vrm
    assert vrm.get("frontAxisNormalized") is False, vrm
    assert not dp.GetAttribute("xformOp:rotateY").IsValid(), "VRM 1.0 must not be rotated"

    body = stage.GetPrimAtPath("/Asset/geo/Body")
    assert body and body.IsA(UsdGeom.Mesh), "expected /Asset/geo/Body mesh"
    binding = UsdSkel.BindingAPI(body)
    assert binding.GetSkeletonRel().GetTargets() == [Sdf.Path("/Asset/skel/Skeleton")]
    assert binding.GetJointWeightsPrimvar().Get(), "missing joint weights"
    # Skinned verts live in skel-root space (glTF ignores the mesh node
    # transform), so the geom bind transform must be identity.
    assert binding.GetGeomBindTransformAttr().Get() == Gf.Matrix4d(1.0)

    mat_rel = UsdShade.MaterialBindingAPI(body).GetDirectBindingRel()
    assert mat_rel.GetTargets() == [Sdf.Path("/Asset/mtl/Body_Mat")], mat_rel.GetTargets()

    # P0.2: the non-skinned Accessory keeps its glTF node placement (x = 1.0).
    acc = stage.GetPrimAtPath("/Asset/geo/Accessory")
    assert acc and acc.IsA(UsdGeom.Mesh), "expected /Asset/geo/Accessory mesh"
    assert not UsdSkel.BindingAPI(acc).GetSkeletonRel().GetTargets()
    xf = acc.GetAttribute("xformOp:transform").Get()
    assert xf is not None and abs(xf.ExtractTranslation()[0] - 1.0) < 1e-6, \
        f"Accessory node transform lost: {xf}"

    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    assert list(skel.GetJointsAttr().Get()) == ["hips", "hips/spine"]
    # P0.1: bind from the (identity) inverse binds, not the non-identity node
    # world transforms.
    binds = skel.GetBindTransformsAttr().Get()
    assert binds and all(b == Gf.Matrix4d(1.0) for b in binds), list(binds)
    assert abs(skel.GetRestTransformsAttr().Get()[0].ExtractTranslation()[1] - 0.5) < 1e-6

    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    assert humanoid.IsValid()
    assert humanoid.GetRelationship("vrm:skeleton").GetTargets() == \
        [Sdf.Path("/Asset/skel/Skeleton")]
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"
    assert humanoid.GetAttribute("vrm:humanBones:spine").Get() == "hips/spine"

    # The typed VrmHumanoidAPI (owned by the sibling vrmSchema bundle since the
    # Phase 1 split) is registered and applied, and the standard bones are
    # schema builtins, not custom attrs.
    assert Usd.SchemaRegistry().IsAppliedAPISchema("VrmHumanoidAPI"), \
        "VrmHumanoidAPI not registered — is the vrmSchema bundle in the session?"
    for api in ("VrmExpressionAPI", "VrmLookAtAPI", "VrmSpringBoneAPI",
                "VrmColliderAPI", "VrmConstraintAPI"):
        assert Usd.SchemaRegistry().IsAppliedAPISchema(api), \
            f"{api} not registered — is the vrmSchema bundle in the session?"
    assert "VrmHumanoidAPI" in humanoid.GetAppliedSchemas(), \
        humanoid.GetAppliedSchemas()
    assert humanoid.GetAttribute("vrm:humanBones:hips").IsCustom() is False, \
        "a standard VRM bone should be a schema builtin, not a custom attribute"


def check_vrm0():
    """The VRM 0.x extension shape (extensions.VRM, humanBones as an array)."""
    stage = _open("vrm0_minimal.vrm")
    dp = stage.GetDefaultPrim()
    vrm = dp.GetCustomData().get("vrm", {})
    assert vrm.get("sourceVersion") == "0.x", vrm
    assert vrm.get("meta"), "VRM 0.x meta should be preserved"
    # Front normalization is baked into the data (no root xformOp). The detailed
    # bake assertions live in check_vrm0_frontbake; here just confirm the policy.
    assert vrm.get("sourceFrontAxis") == "-Z", vrm
    assert vrm.get("frontAxisNormalized") is True, vrm
    assert not dp.GetAttribute("xformOp:rotateY").IsValid(), \
        "VRM 0.x must bake the front rotation, not rotate the root"
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    assert list(skel.GetJointsAttr().Get()) == ["hips", "hips/spine"]
    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"


def check_multiskin_ibm():
    """Two skins unify into one skeleton; bind transforms come from the IBMs."""
    stage = _open("multiskin_ibm.vrm")
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    joints = list(skel.GetJointsAttr().Get())
    assert joints == ["hips", "hips/spine", "hips/spine/extra"], joints
    binds = skel.GetBindTransformsAttr().Get()
    ys = [b.ExtractTranslation()[1] for b in binds]
    assert all(abs(a - b) < 1e-6 for a, b in zip(ys, [0.5, 0.8, 1.0])), ys
    # Both meshes are skinned and bound to the one skeleton.
    for name in ("BodyA", "BodyB"):
        m = stage.GetPrimAtPath(f"/Asset/geo/{name}")
        assert UsdSkel.BindingAPI(m).GetSkeletonRel().GetTargets() == \
            [Sdf.Path("/Asset/skel/Skeleton")], name
    # BodyB's local skin joint 0 (spine) must remap to the unified index 1.
    jiB = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/geo/BodyB")).GetJointIndicesPrimvar().Get()
    assert jiB[0] == 1, f"BodyB joint index not remapped to unified order: {jiB[0]}"


def check_unordered_skel():
    """A child-before-parent skin must be reordered to a valid UsdSkel topology."""
    stage = _open("unordered_skel.vrm")
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    joints = list(skel.GetJointsAttr().Get())
    assert joints == ["hips", "hips/spine"], joints
    valid, reason = UsdSkel.Topology(joints).Validate()
    assert valid, f"invalid skeleton topology: {reason}"
    # Verts were weighted to the skin's local joint 0 (spine); after reorder +
    # remap that must point at the unified spine index (1).
    ji = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/geo/Body")).GetJointIndicesPrimvar().Get()
    assert ji[0] == 1, f"joint index not remapped after topo reorder: {ji[0]}"


def check_expressions():
    """Morph target -> UsdSkelBlendShape, bound on the mesh + an expression."""
    stage = _open("expressions.vrm")

    # Blend shape authored under /Asset/skel/BlendShapes with the right offsets.
    bs_scope = stage.GetPrimAtPath("/Asset/skel/BlendShapes")
    assert bs_scope.IsValid(), "expected /Asset/skel/BlendShapes"
    bs = [p for p in bs_scope.GetChildren() if p.IsA(UsdSkel.BlendShape)]
    assert len(bs) == 1, bs
    offsets = UsdSkel.BlendShape(bs[0]).GetOffsetsAttr().Get()
    assert len(offsets) == 3 and abs(offsets[2][1] - 0.5) < 1e-6, list(offsets)

    # Mesh binding references the blend shape.
    face = UsdSkel.BindingAPI(stage.GetPrimAtPath("/Asset/geo/Face"))
    assert face.GetBlendShapesAttr().Get(), "mesh missing skel:blendShapes"
    assert face.GetBlendShapeTargetsRel().GetTargets() == [bs[0].GetPath()]

    # Expression binds the morph target with weight 1.0.
    happy = stage.GetPrimAtPath("/Asset/rig/Expressions/happy")
    assert happy.IsValid(), "expected /Asset/rig/Expressions/happy"
    assert "VrmExpressionAPI" in happy.GetAppliedSchemas(), happy.GetAppliedSchemas()
    assert happy.GetAttribute("vrm:expressionType").Get() == "preset"
    assert happy.GetAttribute("vrm:expressionType").IsCustom() is False
    # The join key a .vrma clip resolves against: the name the file spelled,
    # not the prim name. For an ASCII preset the two agree, which is exactly
    # why the non-ASCII case below is the one that proves anything.
    assert happy.GetAttribute("vrm:expressionName").Get() == "happy"
    assert happy.GetAttribute("vrm:expressionName").IsCustom() is False
    targets = happy.GetRelationship("vrm:morphTargets").GetTargets()
    assert targets == [bs[0].GetPath()], targets
    weights = happy.GetAttribute("vrm:morphTargetWeights").Get()
    assert weights and abs(weights[0] - 1.0) < 1e-6, list(weights)

    # materialColorBinds: drives Face_Mat emission to red.
    ct = happy.GetRelationship("vrm:materialColorTargets").GetTargets()
    assert ct == [Sdf.Path("/Asset/mtl/Face_Mat")], ct
    assert list(happy.GetAttribute("vrm:materialColorTypes").Get()) == ["emissionColor"]
    cv = happy.GetAttribute("vrm:materialColorValues").Get()
    assert cv and tuple(cv[0]) == (1.0, 0.0, 0.0, 1.0), list(cv)

    # The custom expression "笑顔" holds no ASCII identifier character, so the
    # prim name is a hashed fallback and carries none of the source name. A
    # clip authors the same string on its own side and the two prim names do
    # not match, so vrm:expressionName is the only thing that joins them.
    exprs = stage.GetPrimAtPath("/Asset/rig/Expressions").GetChildren()
    by_name = {p.GetAttribute("vrm:expressionName").Get(): p for p in exprs}
    assert set(by_name) == {"happy", "笑顔"}, sorted(by_name)
    smile = by_name["笑顔"]
    assert smile.GetName() != "笑顔", smile.GetName()
    assert smile.GetName().startswith("Expression_"), smile.GetName()
    assert smile.GetAttribute("vrm:expressionType").Get() == "custom"
    assert smile.GetAttribute("vrm:isBinary").Get() is True


def check_vrm0_expressions():
    """VRM 0.x blendShapeMaster: preset detection + weight 0..100 -> 0..1."""
    stage = _open("vrm0_expressions.vrm")

    bs_scope = stage.GetPrimAtPath("/Asset/skel/BlendShapes")
    assert bs_scope.IsValid(), "expected /Asset/skel/BlendShapes"
    bs = [p for p in bs_scope.GetChildren() if p.IsA(UsdSkel.BlendShape)]
    assert len(bs) == 1, bs

    # The morph mesh carries a skel:skeleton binding (needed to drive the blend
    # shapes), plus the blend-shape binding.
    face = UsdSkel.BindingAPI(stage.GetPrimAtPath("/Asset/geo/Face"))
    assert face.GetSkeletonRel().GetTargets() == ["/Asset/skel/Skeleton"]
    assert face.GetBlendShapeTargetsRel().GetTargets() == [bs[0].GetPath()]

    # presetName "joy" -> preset; weight 100 normalizes to 1.0.
    joy = stage.GetPrimAtPath("/Asset/rig/Expressions/joy")
    assert joy.IsValid(), "expected /Asset/rig/Expressions/joy"
    assert joy.GetAttribute("vrm:expressionType").Get() == "preset"
    # VRM 0.x names a preset in presetName; the canonical name is what crosses,
    # so a 0.x avatar and a 1.0 clip join on the same string.
    assert joy.GetAttribute("vrm:expressionName").Get() == "joy"
    assert joy.GetRelationship("vrm:morphTargets").GetTargets() == [bs[0].GetPath()]
    weights = joy.GetAttribute("vrm:morphTargetWeights").Get()
    assert weights and abs(weights[0] - 1.0) < 1e-6, list(weights)


def check_names():
    """Duplicate / Japanese / empty names sanitize+uniquify without collisions."""
    stage = _open("names.vrm")
    geo = stage.GetPrimAtPath("/Asset/geo")
    meshes = [p for p in geo.GetChildren() if p.IsA(UsdGeom.Mesh)]
    names = [p.GetName() for p in meshes]
    # Five source meshes: "Body", "Body", "Body_2", "顔", "". The third one is
    # the regression: it already spells the suffix the second one is handed, so
    # a uniquifier that counts bases produces "Body_2" twice and `Define`
    # returns the first prim for both -- four meshes, silently.
    assert len(names) == 5, names
    assert len(set(names)) == 5, f"name collision: {names}"
    assert "Body" in names and "Body_2" in names, names
    for n in names:
        assert n and (n[0].isalpha() or n[0] == "_"), f"invalid identifier: {n}"
    mats = stage.GetPrimAtPath("/Asset/mtl").GetChildren()
    assert len({m.GetName() for m in mats}) == 2, [m.GetName() for m in mats]


def check_materials():
    """Alpha BLEND/opacity and alpha MASK -> opacityThreshold."""
    stage = _open("materials.vrm")
    leaf = stage.GetPrimAtPath("/Asset/mtl/Leaf/preview/surface")
    assert leaf.IsValid(), "expected MASK material Leaf"
    thr = leaf.GetAttribute("inputs:opacityThreshold").Get()
    assert thr is not None and abs(thr - 0.3) < 1e-6, f"MASK opacityThreshold: {thr}"
    glass = stage.GetPrimAtPath("/Asset/mtl/Glass/preview/surface")
    assert abs(glass.GetAttribute("inputs:opacity").Get() - 0.3) < 1e-6
    # KHR_materials_unlit: base color via emissive, diffuse/lit response killed,
    # so scene lights don't facet the low-poly surface.
    flat = stage.GetPrimAtPath("/Asset/mtl/Unlit/preview/surface")
    assert flat.IsValid(), "expected unlit material Unlit"
    assert flat.GetAttribute("inputs:diffuseColor").Get() == Gf.Vec3f(0, 0, 0)
    em = flat.GetAttribute("inputs:emissiveColor").Get()
    assert abs(em[0] - 0.9) < 1e-6 and abs(em[2] - 0.1) < 1e-6, em
    assert abs(flat.GetAttribute("inputs:metallic").Get()) < 1e-6

    # The same material in MaterialX: the colour agrees with /preview, but it is
    # reached as glTF emission with the lit response switched off rather than
    # through a PreviewSurface emissive workaround, and glTF alpha coverage is
    # stated in the terminal's own vocabulary (material policy §5.2).
    mx = stage.GetPrimAtPath("/Asset/mtl/Unlit/mtlx/surface")
    assert mx.IsValid(), "expected a MaterialX realization on the unlit material"
    assert mx.GetAttribute("info:id").Get() == "ND_gltf_pbr_surfaceshader"
    assert mx.GetAttribute("inputs:base_color").Get() == Gf.Vec3f(0, 0, 0)
    assert abs(mx.GetAttribute("inputs:specular").Get()) < 1e-6, \
        "a specular lobe would put a highlight on a toon surface"
    assert _vclose(mx.GetAttribute("inputs:emissive").Get(), em), \
        "unlit colour must match the /preview realization"
    assert mx.GetAttribute("inputs:alpha_mode").Get() == 0, "Unlit is OPAQUE"

    # Lit materials carry no MaterialX realization yet (step 2 is unlit-first),
    # so they resolve through the universal terminal.
    assert not stage.GetPrimAtPath("/Asset/mtl/Glass/mtlx").IsValid()


def check_mtlx_textured_unlit():
    """The unlit + textured + alpha-masked path, which is what a VRM avatar is
    actually made of: sampled alpha, the factor multiply, and the sampler wrap
    modes all reach the MaterialX surface only along this route.
    """
    stage = _open("materials.vrm")
    g = "/Asset/mtl/UnlitCutout/mtlx"
    surface = stage.GetPrimAtPath(f"{g}/surface")
    assert surface.IsValid(), "expected a MaterialX realization on UnlitCutout"

    # glTF alpha coverage stated natively: MASK is a cutout the renderer
    # performs, not an ifgreater comparison drawn as a blended surface.
    assert surface.GetAttribute("inputs:alpha_mode").Get() == 1
    cut = surface.GetAttribute("inputs:alpha_cutoff").Get()
    assert abs(cut - 0.4) < 1e-6, f"alpha_cutoff: {cut}"

    # base colour = factor * texture, with the factor's alpha in the 4th
    # channel so the sampled alpha carries it too.
    image = stage.GetPrimAtPath(f"{g}/baseColorImage")
    assert image.GetAttribute("info:id").Get() == "ND_image_color4"
    fattr = image.GetAttribute("inputs:file")
    assert fattr.GetColorSpace() == "srgb_texture", \
        "base colour must be decoded from sRGB"
    # glTF's "repeat" is MaterialX's "periodic"; passing the glTF word through
    # would author an unknown enum that nothing rejects.
    assert image.GetAttribute("inputs:uaddressmode").Get() == "periodic"
    assert image.GetAttribute("inputs:vaddressmode").Get() == "clamp"

    factor = stage.GetPrimAtPath(f"{g}/baseColorFactor")
    assert factor.GetAttribute("info:id").Get() == "ND_multiply_color4"
    assert _vclose(factor.GetAttribute("inputs:in2").Get(),
                   Gf.Vec4f(0.3, 0.6, 0.9, 0.8)), "base colour factor"

    # The /preview realization folds the same factor into UsdUVTexture.scale.
    # Both realizations multiply after the sRGB decode, so the colour agrees
    # even though the shading models do not (material policy §5.4).
    scale = stage.GetPrimAtPath(
        "/Asset/mtl/UnlitCutout/preview/baseColorTexture"
    ).GetAttribute("inputs:scale").Get()
    assert _vclose(scale, factor.GetAttribute("inputs:in2").Get()), \
        f"preview scale {scale} disagrees with the MaterialX factor"

    # Alpha reaches the surface, colour reaches emission: the graph is wired
    # end to end, not merely present.
    alpha_src = UsdShade.Shader(surface).GetInput("alpha").GetConnectedSource()
    assert alpha_src and alpha_src[1] == "outa", f"alpha source {alpha_src}"
    emissive_src = UsdShade.Shader(surface).GetInput("emissive").GetConnectedSource()
    assert emissive_src, "emissive is not driven by the texture chain"
    assert emissive_src[0].GetPrim().GetPath().pathString == f"{g}/baseColorRgb"



def check_material_hierarchy():
    """Material policy §4: the material prim carries identity and binding only;
    every shading node lives inside a per-realization NodeGraph, and the surface
    terminal reaches the network through that graph's output.

    Asserted on the graph *boundary*, never on interior node names (§4.3): a
    realization must stay rewritable without a fixture migration.
    """
    for fixture in ("materials.vrm", "textures.vrm"):
        stage = _open(fixture)
        mtl = stage.GetPrimAtPath("/Asset/mtl")
        assert mtl.IsValid() and mtl.GetChildren(), f"{fixture}: no /Asset/mtl"

        for prim in mtl.GetChildren():
            where = f"{fixture} {prim.GetPath()}"
            mat = UsdShade.Material(prim)
            assert mat, f"{where}: not a Material"

            # Only realization graphs directly below the material: an authored
            # Shader here would be an implementation detail leaking into the
            # material's public shape. /mtlx is present on unlit materials only
            # (P5 step 2 scope), so the set is one of two.
            kids = {c.GetName(): c.GetTypeName() for c in prim.GetChildren()}
            assert kids in ({"preview": "NodeGraph"},
                            {"preview": "NodeGraph", "mtlx": "NodeGraph"}), \
                f"{where}: children {kids}"

            # ...and which of the two it is has to follow from the material, or
            # the assertion above degrades into "either shape is fine" and the
            # unlit-only scope stops being tested at all. /preview's unlit
            # branch is the readable witness: diffuse killed, base colour moved
            # to emissive, no lit response.
            preview_surface = prim.GetPrimAtPath("preview/surface")
            unlit = (preview_surface.GetAttribute("inputs:diffuseColor").Get()
                     == Gf.Vec3f(0, 0, 0)
                     and preview_surface.GetAttribute("inputs:metallic").Get() == 0.0
                     and preview_surface.GetAttribute("inputs:roughness").Get() == 1.0)
            assert ("mtlx" in kids) == unlit, \
                f"{where}: /mtlx present={'mtlx' in kids} but unlit={unlit}"

            preview = UsdShade.NodeGraph(prim.GetChild("preview"))
            src = mat.GetSurfaceOutput().GetConnectedSource()
            assert src, f"{where}: surface terminal not connected"
            assert src[0].GetPrim() == preview.GetPrim() and src[1] == "surface", \
                f"{where}: terminal -> {src[0].GetPrim().GetPath()}.{src[1]}"

            gsrc = preview.GetOutput("surface").GetConnectedSource()
            assert gsrc, f"{where}: /preview exposes no connected surface output"
            inner = gsrc[0].GetPrim()
            assert inner.GetPath().HasPrefix(preview.GetPath()), \
                f"{where}: /preview output leaves the graph: {inner.GetPath()}"

            # The indirection has to stay resolvable: this is what a renderer
            # actually walks, and what a broken terminal would silently cost.
            shader, name, _ = mat.ComputeSurfaceSource()
            assert shader and shader.GetPrim() == inner, \
                f"{where}: surface source resolves to {shader and shader.GetPath()}"
            assert shader.GetIdAttr().Get() == "UsdPreviewSurface", where
            assert name == "surface", f"{where}: surface source name {name}"

            if "mtlx" not in kids:
                continue

            # The MaterialX realization: same boundary shape, reached through
            # the mtlx render context rather than the universal terminal. A
            # renderer that understands MaterialX takes this one in preference,
            # so a broken terminal here does not fall back to /preview — it
            # fails to draw.
            mtlx = UsdShade.NodeGraph(prim.GetChild("mtlx"))
            msrc = mat.GetSurfaceOutput("mtlx").GetConnectedSource()
            assert msrc, f"{where}: mtlx terminal not connected"
            assert msrc[0].GetPrim() == mtlx.GetPrim() and msrc[1] == "surface", \
                f"{where}: mtlx terminal -> {msrc[0].GetPrim().GetPath()}.{msrc[1]}"

            mgsrc = mtlx.GetOutput("surface").GetConnectedSource()
            assert mgsrc, f"{where}: /mtlx exposes no connected surface output"
            minner = mgsrc[0].GetPrim()
            assert minner.GetPath().HasPrefix(mtlx.GetPath()), \
                f"{where}: /mtlx output leaves the graph: {minner.GetPath()}"

            mshader, mname, _ = mat.ComputeSurfaceSource("mtlx")
            assert mshader and mshader.GetPrim() == minner, \
                f"{where}: mtlx source resolves to {mshader and mshader.GetPath()}"
            assert mname == "surface", f"{where}: mtlx source name {mname}"

            # The MaterialX version the graph was written against is declared,
            # so a consumer is not left inferring which node semantics apply.
            assert "MaterialXConfigAPI" in prim.GetAppliedSchemas(), where
            assert prim.GetAttribute("config:mtlx:version").Get() == "1.39", where

        # Bindings target the material prim itself, never a node inside it.
        for prim in stage.Traverse():
            if not prim.IsA(UsdGeom.Mesh):
                continue
            for target in UsdShade.MaterialBindingAPI(
                    prim).GetDirectBindingRel().GetTargets():
                assert UsdShade.Material(stage.GetPrimAtPath(target)), \
                    f"{fixture}: {prim.GetPath()} binds non-material {target}"


def check_texture_transform():
    """KHR_texture_transform lands on the same texel in both realizations, and
    that texel is the one glTF names.

    Asserted by evaluating the two node definitions against glTF's own matrix
    rather than against each other: `UsdTransform2d` computes
    `rotate2d(in * scale, -rotation) + translation` while MaterialX's `place2d`
    computes `rotate2d((uv - pivot) / scale, rotate) - offset + pivot`, so they
    divide where the other multiplies and subtract where it adds. Nothing about
    passing the glTF triple to both is safe, and an identity transform -- which
    is every transform in the vendored corpus -- hides all of it.
    """
    import math

    # The values authored into the fixture.
    rot = 1.5707963
    scale = (2.0, 4.0)
    offset = (0.25, 0.125)
    cos_r, sin_r = math.cos(rot), math.sin(rot)

    def rotate2d(v, degrees):
        """MaterialX's rotate2d: clockwise, and it takes degrees."""
        a = math.radians(degrees)
        ca, sa = math.cos(a), math.sin(a)
        return (ca * v[0] + sa * v[1], -sa * v[0] + ca * v[1])

    def gltf_sample(uv):
        """Where glTF says to sample, given its T*R*S matrix on glTF UVs."""
        u, v = uv
        return (scale[0] * cos_r * u + scale[1] * sin_r * v + offset[0],
                -scale[0] * sin_r * u + scale[1] * cos_r * v + offset[1])

    def flip(p):
        return (p[0], 1.0 - p[1])

    stage = _open("materials.vrm")

    xf = stage.GetPrimAtPath("/Asset/mtl/UnlitPlaced/preview/baseColorTexture_xf")
    assert xf.IsValid(), "expected a UsdTransform2d on the placed material"
    p_scale = xf.GetAttribute("inputs:scale").Get()
    p_rot = xf.GetAttribute("inputs:rotation").Get()
    p_trans = xf.GetAttribute("inputs:translation").Get()

    place = stage.GetPrimAtPath("/Asset/mtl/UnlitPlaced/mtlx/baseColorPlace")
    assert place.IsValid(), "expected a place2d on the placed material"
    m_scale = place.GetAttribute("inputs:scale").Get()
    m_rot = place.GetAttribute("inputs:rotate").Get()
    m_offset = place.GetAttribute("inputs:offset").Get()
    assert place.GetAttribute("inputs:operationorder").Get() in (None, 0), \
        "the maths below assumes place2d's default SRT order"

    def preview_sample(st):
        v = rotate2d((st[0] * p_scale[0], st[1] * p_scale[1]), -p_rot)
        return (v[0] + p_trans[0], v[1] + p_trans[1])

    def mtlx_sample(st):
        v = rotate2d((st[0] / m_scale[0], st[1] / m_scale[1]), m_rot)
        return (v[0] - m_offset[0], v[1] - m_offset[1])

    for uv in ((0.0, 0.0), (1.0, 1.0), (0.3, 0.7), (0.25, 0.9)):
        st = flip(uv)                 # what the importer wrote into primvars:st
        want = flip(gltf_sample(uv))  # what USD must sample to match glTF
        assert _vclose(preview_sample(st), want, 1e-4), \
            f"/preview samples {preview_sample(st)} for uv {uv}, want {want}"
        assert _vclose(mtlx_sample(st), want, 1e-4), \
            f"/mtlx samples {mtlx_sample(st)} for uv {uv}, want {want}"

    # The rotation is stated in degrees by both nodes; glTF states it in
    # radians. Passing 1.5708 through unconverted is a 90-degree rotation
    # authored as 1.57 degrees, which looks like no rotation at all.
    assert abs(abs(p_rot) - 90.0) < 1e-3, f"preview rotation {p_rot} is not in degrees"
    assert abs(abs(m_rot) - 90.0) < 1e-3, f"mtlx rotate {m_rot} is not in degrees"


def check_mtlx_node_ids():
    """Every `info:id` inside /mtlx names a real MaterialX node definition.

    A misspelled `ND_*` id is the cheapest mistake to make here and the most
    expensive to notice: nothing rejects it at author time, the stage opens, and
    the material simply fails to draw in a MaterialX-aware renderer. Sdr is the
    same registry the renderer consults, so asking it is the check.
    """
    from pxr import Sdr

    registry = Sdr.Registry()
    if not registry.GetShaderNodeByIdentifier("ND_gltf_pbr_surfaceshader"):
        print("    (MaterialX node definitions unavailable; skipped)")
        return

    seen = 0
    for fixture in ("materials.vrm", "textures.vrm"):
        stage = _open(fixture)
        for prim in stage.Traverse():
            if "mtlx" not in prim.GetPath().pathString.split("/"):
                continue
            shader = UsdShade.Shader(prim)
            if not shader:
                continue
            node_id = shader.GetIdAttr().Get()
            assert node_id, f"{fixture} {prim.GetPath()}: no info:id"
            node = registry.GetShaderNodeByIdentifier(node_id)
            assert node, \
                f"{fixture} {prim.GetPath()}: unknown MaterialX node '{node_id}'"

            # A wrong input name fails even more quietly than a wrong node id:
            # nothing rejects it, the node keeps its default, and the material
            # renders as though the value had never been authored. Rename
            # `emissive` to `emissiveColor` and every unlit avatar goes black.
            declared_in = set(node.GetShaderInputNames())
            for inp in shader.GetInputs():
                assert inp.GetBaseName() in declared_in, \
                    (f"{fixture} {prim.GetPath()}: '{node_id}' has no input "
                     f"'{inp.GetBaseName()}' ({sorted(declared_in)})")
            declared_out = set(node.GetShaderOutputNames())
            for out in shader.GetOutputs():
                # A surfaceshader output is spelled `surface` in USD.
                assert out.GetBaseName() in declared_out | {"surface"}, \
                    (f"{fixture} {prim.GetPath()}: '{node_id}' has no output "
                     f"'{out.GetBaseName()}' ({sorted(declared_out)})")
            seen += 1
    assert seen, "no /mtlx shader nodes found to verify"


def check_springbone():
    """VRM SpringBone -> /Asset/rig/SecondaryMotion (chains + colliders, data)."""
    stage = _open("springbone.vrm")
    sm = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion")
    assert sm.IsValid(), "expected /Asset/rig/SecondaryMotion"
    assert sm.GetCustomData().get("vrm", {}).get("springBone", {}).get("raw")

    hair = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion/SpringBones/Hair")
    assert hair.IsValid(), "expected SpringBones/Hair"
    assert "VrmSpringBoneAPI" in hair.GetAppliedSchemas(), hair.GetAppliedSchemas()
    assert list(hair.GetAttribute("vrm:joints").Get()) == \
        ["hips/spine/hair1", "hips/spine/hair1/hair2"]
    stiff = list(hair.GetAttribute("vrm:stiffness").Get())
    assert abs(stiff[0] - 1.0) < 1e-6 and abs(stiff[1] - 0.8) < 1e-6, stiff
    assert abs(hair.GetAttribute("vrm:gravityPower").Get()[0] - 0.5) < 1e-6
    assert hair.GetAttribute("vrm:center").Get() == "springCenter"

    head = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion/Colliders/Head")
    assert head.IsValid(), "expected Colliders/Head"
    assert hair.GetRelationship("vrm:colliderGroups").GetTargets() == [head.GetPath()]
    col = stage.GetPrimAtPath(
        "/Asset/rig/SecondaryMotion/Colliders/Head/Collider_0")
    assert "VrmColliderAPI" in col.GetAppliedSchemas(), col.GetAppliedSchemas()
    assert col.GetAttribute("vrm:shape").Get() == "sphere"
    assert abs(col.GetAttribute("vrm:radius").Get() - 0.1) < 1e-6
    assert col.GetAttribute("vrm:node").Get() == "hips/spine"


def check_shared_accessor():
    """Two primitives sharing one accessor are compacted to their used verts."""
    stage = _open("shared_accessor.vrm")
    for name in ("Quad_0", "Quad_1"):
        m = UsdGeom.Mesh(stage.GetPrimAtPath(f"/Asset/geo/{name}"))
        assert m, name
        pts = m.GetPointsAttr().Get()
        fvi = m.GetFaceVertexIndicesAttr().Get()
        # Compacted: exactly the 3 referenced verts, topology covering them all.
        assert len(pts) == 3, (name, len(pts))
        assert max(fvi) == len(pts) - 1, (name, list(fvi), len(pts))


def check_animation():
    """A glTF rotation clip -> UsdSkelAnimation bound to the skeleton."""
    stage = _open("animation.vrm")
    anim = UsdSkel.Animation(stage.GetPrimAtPath("/Asset/skel/Animations/wave"))
    assert anim, "expected /Asset/skel/Animations/wave"
    assert list(anim.GetJointsAttr().Get()) == ["hips/spine"]

    rattr = anim.GetRotationsAttr()
    ts = rattr.GetTimeSamples()
    assert ts and abs(ts[0] - 0.0) < 1e-6 and abs(ts[-1] - 30.0) < 1e-6, ts
    q0 = rattr.Get(0.0)[0]
    assert abs(q0.GetReal() - 1.0) < 1e-4, q0          # identity at t=0
    qn = rattr.Get(30.0)[0]
    assert abs(qn.GetReal() - 0.7071) < 1e-3, qn       # 90 deg about Z at t=1s
    assert abs(qn.GetImaginary()[2] - 0.7071) < 1e-3, qn

    # Bound so it plays, with the stage time range set.
    src = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/skel/Skeleton")).GetAnimationSourceRel()
    assert src.GetTargets() == [Sdf.Path("/Asset/skel/Animations/wave")], src.GetTargets()
    assert abs(stage.GetStartTimeCode() - 0.0) < 1e-6
    assert abs(stage.GetEndTimeCode() - 30.0) < 1e-6


def check_lookat():
    """VRM lookAt -> /Asset/rig/LookAt with eye tokens + preserved curves."""
    stage = _open("lookat.vrm")
    la = stage.GetPrimAtPath("/Asset/rig/LookAt")
    assert la.IsValid(), "expected /Asset/rig/LookAt"
    assert "VrmLookAtAPI" in la.GetAppliedSchemas(), la.GetAppliedSchemas()
    assert la.GetAttribute("vrm:type").Get() == "bone"
    assert la.GetAttribute("vrm:leftEye").Get() == "hips/spine/head/leftEye"
    assert la.GetAttribute("vrm:rightEye").Get() == "hips/spine/head/rightEye"
    assert la.GetRelationship("vrm:skeleton").GetTargets() == \
        [Sdf.Path("/Asset/skel/Skeleton")]
    raw = la.GetCustomData().get("vrm", {}).get("lookAt", {}).get("raw")
    assert raw and "rangeMapHorizontalInner" in raw, "lookAt curves not preserved"


def check_textures():
    """Embedded base-color texture -> UsdUVTexture + st reader; MToon metadata."""
    stage = _open("textures.vrm")
    mat = stage.GetPrimAtPath("/Asset/mtl/Skin")
    surf = stage.GetPrimAtPath("/Asset/mtl/Skin/preview/surface")
    tex = stage.GetPrimAtPath("/Asset/mtl/Skin/preview/baseColorTexture")
    assert mat.IsValid() and surf.IsValid() and tex.IsValid()

    assert tex.GetAttribute("info:id").Get() == "UsdUVTexture"
    f = tex.GetAttribute("inputs:file").Get()
    assert f and ".vrm[" in f.path and f.path.endswith(".png]"), f
    resolved = Ar.GetResolver().Resolve(f.path)
    assert resolved, f
    asset = Ar.GetResolver().OpenAsset(resolvedPath=resolved)
    assert asset and asset.GetSize() > 0, f
    assert tex.GetAttribute("inputs:sourceColorSpace").Get() == "sRGB"
    assert tex.GetAttribute("inputs:wrapS").Get() == "repeat"
    assert tex.GetAttribute("inputs:wrapT").Get() == "clamp"
    assert tex.GetAttribute("inputs:scale").Get() == Gf.Vec4f(0.5, 0.25, 0.75, 0.6)

    # diffuseColor <- texture.rgb, and st <- stReader.result.
    conn = surf.GetAttribute("inputs:diffuseColor").GetConnections()
    assert conn == [
        Sdf.Path("/Asset/mtl/Skin/preview/baseColorTexture.outputs:rgb")], conn
    assert stage.GetPrimAtPath("/Asset/mtl/Skin/preview/stReader").IsValid()
    stc = tex.GetAttribute("inputs:st").GetConnections()
    assert stc == [
        Sdf.Path("/Asset/mtl/Skin/preview/stReader.outputs:result")], stc

    # MToon preserved as metadata.
    assert mat.GetAttribute("vrm:shaderModel").Get() == "MToon"
    assert mat.GetCustomData().get("vrm", {}).get("mtoon", {}).get("raw")


def check_portable_package():
    """Package command copies temp-cache textures and rewrites paths relative."""
    assert _package_member_path(r"textures\base", "textures_dir") == "textures/base"
    for bad in ("/escape.usda", r"\escape.usda", r"C:escape.usda",
                r"C:\escape.usda", "../escape.usda", r"..\escape.usda"):
        try:
            _package_member_path(bad, "stage_name")
        except ValueError:
            pass
        else:
            raise AssertionError(f"accepted escaping package path: {bad!r}")

    with tempfile.TemporaryDirectory() as tmp:
        package_dir = pathlib.Path(tmp) / "textures_package"
        report = package_stage(FIXTURES / "textures.vrm", package_dir)

        assert report["summary"]["texturesPackaged"] == 1, report
        assert report["summary"]["missingAssets"] == 0, report
        assert report["pathPolicy"]["textureAssetPaths"] == "relative-to-package-root"

        stage_path = package_dir / report["stage"]
        report_path = package_dir / "package_report.json"
        assert stage_path.exists(), stage_path
        assert report_path.exists(), report_path

        packaged_stage = Usd.Stage.Open(str(stage_path))
        assert packaged_stage, f"failed to open packaged stage: {stage_path}"
        tex = packaged_stage.GetPrimAtPath(
            "/Asset/mtl/Skin/preview/baseColorTexture")
        asset = tex.GetAttribute("inputs:file").Get()
        assert asset.path.startswith("textures/"), asset
        assert not pathlib.Path(asset.path).is_absolute(), asset
        assert (package_dir / asset.path).exists(), asset

        entry = report["assets"][0]
        assert entry["status"] == "packaged", entry
        assert entry["portablePath"] == asset.path, entry
        assert len(entry["sha256"]) == 64, entry


def check_vrm0_frontbake():
    """VRM 0.x front bake: 180-about-Y baked into data, not a root xformOp."""
    stage = _open("vrm0_frontbake.vrm")
    dp = stage.GetDefaultPrim()
    assert not dp.GetAttribute("xformOp:rotateY").IsValid(), "must bake, not rotate root"
    assert dp.GetCustomData().get("vrm", {}).get("frontAxisNormalized") is True

    # Skinned mesh points rotated 180 about Y: (x,y,z) -> (-x,y,-z).
    body = UsdGeom.Mesh(stage.GetPrimAtPath("/Asset/geo/Body"))
    pts = body.GetPointsAttr().Get()
    assert _vclose(pts[0], (0.5, 0.0, -1.0)), list(pts)
    assert _vclose(pts[2], (0.0, 1.0, -1.0)), list(pts)

    # Root (hips) rest carries the rotation (+ keeps its translation); bind too.
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    rest0 = skel.GetRestTransformsAttr().Get()[0]
    assert _vclose(rest0.TransformDir(Gf.Vec3d(1, 0, 0)), (-1, 0, 0)), rest0
    assert _vclose(rest0.ExtractTranslation(), (0, 0.5, 0)), rest0
    bind0 = skel.GetBindTransformsAttr().Get()[0]
    assert _vclose(bind0.TransformDir(Gf.Vec3d(0, 0, 1)), (0, 0, -1)), bind0

    # Embedded clip's root (hips) track is baked: rotation 90 -> 90+180 = 270 deg
    # about Y, translation (1,0.5,0) -> (-1,0.5,0).
    anim = UsdSkel.Animation(stage.GetPrimAtPath("/Asset/skel/Animations/move"))
    assert list(anim.GetJointsAttr().Get()) == ["hips"]
    t1 = anim.GetTranslationsAttr().Get(30.0)[0]
    assert _vclose(t1, (-1.0, 0.5, 0.0)), t1
    q = anim.GetRotationsAttr().Get(30.0)[0]
    qm = Gf.Matrix3d(Gf.Quatd(q.GetReal(), Gf.Vec3d(*q.GetImaginary())))
    exp = Gf.Matrix3d(Gf.Rotation(Gf.Vec3d(0, 1, 0), 270.0))
    assert _vclose(Gf.Vec3d(1, 0, 0) * qm, Gf.Vec3d(1, 0, 0) * exp), q

    # Skinning still reproduces the (rotated) source at the rest pose (t=0): the
    # bake is internally consistent across points + bind + rest + the bound clip.
    cache = UsdSkel.Cache()
    cache.Populate(UsdSkel.Root(dp), Usd.PrimDefaultPredicate)
    skelQ = cache.GetSkelQuery(skel)
    skinQ = cache.GetSkinningQuery(body.GetPrim())
    xforms = skelQ.ComputeSkinningTransforms(Usd.TimeCode(0.0))
    skinned = Vt.Vec3fArray(list(pts))
    assert skinQ.ComputeSkinnedPoints(xforms, skinned, Usd.TimeCode(0.0))
    for i in range(len(pts)):
        assert _vclose(skinned[i], pts[i], 1e-4), (i, skinned[i], pts[i])

    # Spring gravityDir is a model-space direction, so it's baked too:
    # the "wind" (1,0,0) becomes (-1,0,0) for the now-+Z avatar.
    spring = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion/SpringBones/Wind")
    assert spring.IsValid(), "expected baked spring at .../SpringBones/Wind"
    gdir = spring.GetAttribute("vrm:gravityDir").Get()
    assert gdir and _vclose(gdir[0], (-1.0, 0.0, 0.0)), list(gdir)


def check_constraints():
    """VRMC_node_constraint -> /Asset/rig/Constraints (type/source/axis/weight)."""
    stage = _open("constraints.vrm")
    con = stage.GetPrimAtPath("/Asset/rig/Constraints/head_roll")
    assert con.IsValid(), "expected /Asset/rig/Constraints/head_roll"
    assert "VrmConstraintAPI" in con.GetAppliedSchemas(), con.GetAppliedSchemas()
    assert con.GetAttribute("vrm:type").Get() == "roll"
    assert con.GetAttribute("vrm:constrained").Get() == "hips/spine/head"
    assert con.GetAttribute("vrm:source").Get() == "hips/spine"
    assert con.GetAttribute("vrm:axis").Get() == "X"
    assert abs(con.GetAttribute("vrm:weight").Get() - 0.8) < 1e-6
    raw = con.GetCustomData().get("vrm", {}).get("constraint", {}).get("raw")
    assert raw and "rollAxis" in raw, "constraint raw block not preserved"


def check_badext():
    """A semantically broken VRM humanoid must warn+skip, never crash."""
    stage = _open("badext.vrm")
    assert stage.GetPrimAtPath("/Asset").IsValid()
    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    # The valid bone maps; the out-of-range one is dropped. spine is a builtin of
    # the applied VrmHumanoidAPI, so the attribute always exists — "dropped" now
    # means it carries no authored value rather than being an invalid attribute.
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"
    assert not humanoid.GetAttribute("vrm:humanBones:spine").HasAuthoredValue(), \
        "out-of-range humanoid bone should be skipped (no authored value)"
    # The raw block is still preserved even though parts were unusable.
    assert stage.GetDefaultPrim().GetCustomData().get("vrm", {}).get("rawExtension")
    # Diagnostic report: the dropped out-of-range bone is surfaced on /Asset.
    warnings = stage.GetDefaultPrim().GetCustomData().get("vrm", {}).get("warnings")
    assert warnings and any("spine" in w and "skipped" in w for w in warnings), warnings


def main() -> int:
    plugin_path = os.environ.get("PXR_PLUGINPATH_NAME")
    if plugin_path:
        Plug.Registry().RegisterPlugins(plugin_path.split(os.pathsep))
    assert Sdf.FileFormat.FindByExtension("vrm"), \
        "usdVrm SdfFileFormat is not registered"

    for check in (check_minimal, check_vrm0, check_multiskin_ibm,
                  check_unordered_skel, check_expressions,
                  check_vrm0_expressions, check_vrm0_frontbake,
                  check_textures, check_portable_package, check_animation,
                  check_lookat, check_springbone, check_names, check_materials,
                  check_material_hierarchy, check_mtlx_textured_unlit,
                  check_texture_transform, check_mtlx_node_ids,
                  check_constraints,
                  check_shared_accessor, check_badext):
        check()
        print(f"  {check.__name__}: OK")
    print("usdVrm smoke tests: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
