#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Author the motion corpus: the recorded capture traces Motion Phase D replays.

Why these are synthesised rather than recorded from a real capture rig: the VRM
corpus is licence-gated (see plugins/usdVrmFileFormat/tests/corpus/CORPUS.md),
and a motion corpus sourced from a commercial capture SDK or a performer would
inherit exactly the same problem -- a fixture nobody outside the project can
redistribute is a fixture CI cannot run. These traces are generated by closed-form
maths in this file, so they are Apache-2.0 like the rest of the repo, byte-stable
across machines, and reviewable in a diff.

What they are not: real capture data. They reproduce the *shapes* a live source
produces -- dropouts, confidence collapse, irregular arrival, a partial rig, an
explicit root velocity -- not the noise characteristics of any particular
device. Validating against a real rig stays open work, and it needs an adapter
(motion policy §8.2), not a fixture.

The output must match motionRuntime's own writer byte for byte; the corpus test
(`motionRuntime_corpus`) enforces that. Run:

    python libs/motionRuntime/tools/generate_traces.py

`manifest.json` is maintained from here too. Its measured fields (frame counts,
durations, observed bones, digests) are re-derived from the traces on every run
and compared under --check, so the manifest cannot quietly stop describing the
corpus; its prose fields (`pins`, `tags`, the top-level notes) are hand-written
and preserved untouched.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import pathlib
import sys

MANIFEST_NAME = "manifest.json"

# Must equal motionRuntime's CaptureTraceFormatVersion. The corpus test re-emits
# every committed trace through the C++ writer and compares bytes, so a version
# that drifted from the header fails there rather than authoring a fixture the
# reader would refuse.
TRACE_FORMAT_VERSION = 3

# The VRM 1.0 humanoid vocabulary in motionCore's enum order. The trace writer
# emits bones in this order, so the corpus must too.
#
# This is a second copy of motionCore's HumanBone enum, and the C++ side stays
# the single source of truth: motionRuntime_corpus re-emits every committed trace
# through the C++ writer and compares bytes, so an order that drifted from the
# enum would fail there rather than silently authoring a mis-ordered fixture.
BONE_ORDER = [
    "hips", "spine", "chest", "upperChest", "neck", "head", "leftEye",
    "rightEye", "jaw",
    "leftUpperLeg", "leftLowerLeg", "leftFoot", "leftToes", "rightUpperLeg",
    "rightLowerLeg", "rightFoot", "rightToes",
    "leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand",
    "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand",
    "leftThumbMetacarpal", "leftThumbProximal", "leftThumbDistal",
    "leftIndexProximal", "leftIndexIntermediate", "leftIndexDistal",
    "leftMiddleProximal", "leftMiddleIntermediate", "leftMiddleDistal",
    "leftRingProximal", "leftRingIntermediate", "leftRingDistal",
    "leftLittleProximal", "leftLittleIntermediate", "leftLittleDistal",
    "rightThumbMetacarpal", "rightThumbProximal", "rightThumbDistal",
    "rightIndexProximal", "rightIndexIntermediate", "rightIndexDistal",
    "rightMiddleProximal", "rightMiddleIntermediate", "rightMiddleDistal",
    "rightRingProximal", "rightRingIntermediate", "rightRingDistal",
    "rightLittleProximal", "rightLittleIntermediate", "rightLittleDistal",
]
BONE_INDEX = {name: index for index, name in enumerate(BONE_ORDER)}

# A body-tracking rig of the kind these traces model: torso, limbs, feet. No
# fingers, no eyes, no jaw -- which is the point of the coverage diagnostic.
BODY_RIG = [
    "hips", "spine", "chest", "neck", "head",
    "leftUpperLeg", "leftLowerLeg", "leftFoot", "leftToes",
    "rightUpperLeg", "rightLowerLeg", "rightFoot", "rightToes",
    "leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand",
    "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand",
]
UPPER_BODY_RIG = [
    "hips", "spine", "chest", "neck", "head",
    "leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand",
    "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand",
]
LEFT_ARM_CHAIN = ["leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand"]
EXTREMITIES = ["leftHand", "rightHand", "leftToes", "rightToes"]


def quaternion(axis: tuple[float, float, float], degrees: float
               ) -> tuple[float, float, float, float]:
    """Axis-angle to (w, x, y, z), normalised."""
    radians = math.radians(degrees) * 0.5
    length = math.sqrt(sum(component * component for component in axis)) or 1.0
    sin = math.sin(radians) / length
    return (math.cos(radians), axis[0] * sin, axis[1] * sin, axis[2] * sin)


def walk_pose(bones: list[str], phase: float) -> dict[str, tuple[float, ...]]:
    """One frame of a 1 Hz walk cycle. Closed form, so it is reproducible."""
    swing = math.sin(phase)
    counter = math.sin(phase + math.pi)
    rotations: dict[str, tuple[float, ...]] = {}

    for bone in bones:
        if bone == "hips":
            rotations[bone] = quaternion((0.0, 1.0, 0.0), 3.0 * swing)
        elif bone == "spine":
            rotations[bone] = quaternion((0.0, 1.0, 0.0), -1.5 * swing)
        elif bone == "chest":
            rotations[bone] = quaternion((0.0, 1.0, 0.0), -2.5 * swing)
        elif bone == "neck":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 2.0 * counter)
        elif bone == "head":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 1.0 * swing)
        elif bone == "leftUpperLeg":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 25.0 * swing)
        elif bone == "rightUpperLeg":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 25.0 * counter)
        elif bone == "leftLowerLeg":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), -30.0 * max(swing, 0.0))
        elif bone == "rightLowerLeg":
            rotations[bone] = quaternion((1.0, 0.0, 0.0),
                                         -30.0 * max(counter, 0.0))
        elif bone == "leftFoot":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 10.0 * counter)
        elif bone == "rightFoot":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 10.0 * swing)
        elif bone in ("leftToes", "rightToes"):
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 4.0 * swing)
        elif bone == "leftUpperArm":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 20.0 * counter)
        elif bone == "rightUpperArm":
            rotations[bone] = quaternion((1.0, 0.0, 0.0), 20.0 * swing)
        elif bone in ("leftLowerArm", "rightLowerArm"):
            rotations[bone] = quaternion((1.0, 0.0, 0.0), -12.0 * abs(swing))
        elif bone in ("leftShoulder", "rightShoulder"):
            rotations[bone] = quaternion((0.0, 0.0, 1.0), 2.0 * swing)
        else:
            rotations[bone] = quaternion((0.0, 1.0, 0.0), 1.0 * swing)
    return rotations


class Frame:
    def __init__(self, timestamp: float) -> None:
        self.timestamp = timestamp
        self.rotations: dict[str, tuple[float, ...]] = {}
        self.confidence: dict[str, float] = {}
        self.has_confidence = False
        self.root_position: tuple[float, float, float] | None = None
        self.root_velocity: tuple[float, float, float] | None = None
        self.contacts: tuple[str, str] | None = None
        # Name -> weight. A name absent from a frame was not reported by that
        # frame, which is not the same as a weight of 0 -- see CaptureTrace.h.
        self.expressions: dict[str, float] = {}


def render(frames: list[Frame], provider: str, protocol: str, source_id: str,
           frame_rate: float) -> str:
    """Emit the trace exactly as motionRuntime's WriteCaptureTrace would."""
    out: list[str] = [f"!motion-capture-trace {TRACE_FORMAT_VERSION}"]
    out.append(f"provider {provider}")
    out.append(f"protocol {protocol}")
    out.append(f"sourceId {source_id}")
    out.append(f"frameRate {frame_rate:.6f}")

    for frame in frames:
        out.append("")
        out.append(f"t {frame.timestamp:.6f}")
        if frame.root_position is not None:
            x, y, z = frame.root_position
            out.append(f"root pos {x:.6f} {y:.6f} {z:.6f}")
        if frame.root_velocity is not None:
            x, y, z = frame.root_velocity
            out.append(f"root vel {x:.6f} {y:.6f} {z:.6f}")
        if frame.contacts is not None:
            out.append(f"contacts {frame.contacts[0]} {frame.contacts[1]}")
        for bone in sorted(frame.rotations, key=lambda name: BONE_INDEX[name]):
            w, x, y, z = frame.rotations[bone]
            line = f"b {bone} {w:.6f} {x:.6f} {y:.6f} {z:.6f}"
            if frame.has_confidence:
                line += f" {frame.confidence.get(bone, 1.0):.6f}"
            out.append(line)
        # Name order, which is the order ExpressionWeights keeps them in and so
        # the order the C++ writer emits.
        for name in sorted(frame.expressions):
            out.append(f"e {name} {frame.expressions[name]:.6f}")

    return "\n".join(out) + "\n"


def build_walk(bones: list[str], frame_count: int, frame_rate: float,
               *, speed: float = 1.0, intervals: list[float] | None = None
               ) -> list[Frame]:
    frames: list[Frame] = []
    timestamp = 0.0
    for index in range(frame_count):
        if intervals is not None and index > 0:
            timestamp += intervals[(index - 1) % len(intervals)]
        elif index > 0:
            timestamp += 1.0 / frame_rate
        phase = 2.0 * math.pi * timestamp
        frame = Frame(timestamp)
        frame.rotations = walk_pose(bones, phase)
        frame.root_position = (
            0.0,
            0.9 + 0.02 * math.sin(2.0 * phase),
            speed * timestamp,
        )
        in_contact = math.sin(phase) >= 0.0
        frame.contacts = (
            "contact" if in_contact else "free",
            "free" if in_contact else "contact",
        )
        frames.append(frame)
    return frames


def trace_walk() -> str:
    """The happy path: a clean, complete 30 Hz body capture."""
    frames = build_walk(BODY_RIG, 61, 30.0)
    return render(frames, "example.synthetic", "replay", "walk-clean-01", 30.0)


def trace_dropout() -> str:
    """The left arm chain vanishes for half a second, then returns.

    This is what a self-occluded limb looks like to a body tracker, and it is
    the fixture MissingBonePolicy is judged against: held, the arm freezes;
    unbound, it falls back to the target rig's rest pose.
    """
    frames = build_walk(BODY_RIG, 61, 30.0)
    for index, frame in enumerate(frames):
        if 20 <= index < 35:
            for bone in LEFT_ARM_CHAIN:
                frame.rotations.pop(bone, None)
    return render(frames, "example.synthetic", "replay", "walk-dropout-01", 30.0)


def trace_low_confidence() -> str:
    """Every bone carries a confidence; the extremities collapse mid-clip.

    A tracker usually degrades before it drops a bone outright. Gating on
    confidence is what turns that degradation into an explicit decision rather
    than believable-looking garbage.
    """
    frames = build_walk(BODY_RIG, 61, 30.0)
    for index, frame in enumerate(frames):
        frame.has_confidence = True
        for bone in frame.rotations:
            score = 0.95
            if bone in EXTREMITIES:
                score = 0.3 if 15 <= index < 45 else 0.85
            elif bone in ("leftLowerArm", "rightLowerArm"):
                score = 0.6
            frame.confidence[bone] = score
    return render(frames, "example.synthetic", "replay", "walk-confidence-01",
                  30.0)


def trace_jitter() -> str:
    """Frames arrive on an irregular cadence around a nominal 30 Hz.

    Timestamps still increase -- a trace records what was captured, and delivery
    order is a property of the transport, not the recording. What this fixture
    pins is that bracketed sampling and frame-rate-independent smoothing do not
    assume a uniform step.
    """
    intervals = [0.0333, 0.0410, 0.0295, 0.0333, 0.0500, 0.0250]
    frames = build_walk(BODY_RIG, 48, 30.0, intervals=intervals)
    return render(frames, "example.synthetic", "replay", "walk-jitter-01", 30.0)


def trace_upper_body() -> str:
    """A rig that solves no legs at all -- the coverage-reporting fixture."""
    frames = build_walk(UPPER_BODY_RIG, 46, 30.0, speed=0.0)
    for frame in frames:
        frame.root_position = (0.0, 0.9, 0.0)
        frame.contacts = None
    return render(frames, "example.synthetic", "replay", "upper-body-01", 30.0)


def trace_root_velocity() -> str:
    """The root reports its own velocity, so nothing has to be derived.

    Exercises RootMotionIntake::Passthrough against DeriveVelocity, and gives
    PoseBuffer::SampleExtrapolated a reported velocity to work from.
    """
    frames = build_walk(BODY_RIG, 46, 30.0, speed=1.4)
    for frame in frames:
        frame.root_velocity = (0.0, 0.0, 1.4)
    return render(frames, "example.synthetic", "replay", "walk-rootvel-01", 30.0)


def trace_expressions() -> str:
    """A face channel beside the body -- and a name that comes and goes.

    Three shapes in one fixture, because each is a rule rather than a value:

    `happy` is reported on every frame, so it is the ordinary case. `aa` follows
    a vowel envelope and reaches exactly 0 in the middle -- reported and zero,
    which a reader must not confuse with unreported. `blink` is reported only
    across five frames, which is unreported on either side of them, and is what
    separates the two: a consumer that treats absence as 0 sees the same clip as
    one that holds the last weight, until this fixture.

    `studio.browRaise` is deliberately not a VRM preset name. The expression
    vocabulary is open -- a VMC sender's blend-shape names are its model's, not a
    spec's -- so a corpus of preset names only would let a reader that quietly
    validated against a preset table keep passing.
    """
    frames = build_walk(BODY_RIG, 46, 30.0, speed=0.0)
    for index, frame in enumerate(frames):
        frame.root_position = (0.0, 0.9, 0.0)
        frame.contacts = None
        phase = 2.0 * math.pi * index / 30.0
        frame.expressions["happy"] = 0.4
        # Exactly 0 where the sine is, rather than nearly 0: the point of the
        # channel is that a reported zero is a value.
        frame.expressions["aa"] = round(0.5 * (1.0 - math.cos(phase)), 6)
        frame.expressions["studio.browRaise"] = round(0.25 * abs(
            math.sin(phase)), 6)
        if 20 <= index < 25:
            frame.expressions["blink"] = round(
                1.0 - abs(index - 22) / 2.0, 6)
    return render(frames, "example.synthetic", "replay", "expressions-01", 30.0)


TRACES = {
    "expressions-30hz.trace": trace_expressions,
    "walk-clean-30hz.trace": trace_walk,
    "walk-dropout-30hz.trace": trace_dropout,
    "walk-low-confidence-30hz.trace": trace_low_confidence,
    "walk-jitter-30hz.trace": trace_jitter,
    "upper-body-30hz.trace": trace_upper_body,
    "walk-root-velocity-30hz.trace": trace_root_velocity,
}


def measure(text: str) -> dict:
    """Read back out of a trace everything the manifest claims about it.

    The manifest says its values are "measured from the committed files, never
    guessed". Nothing enforced that, so the numbers were free to drift the next
    time a fixture changed shape -- which is exactly the failure a provenance
    manifest exists to prevent. This is the measurement; `--check` is the gate.
    """
    timestamps: list[float] = []
    bones: set[str] = set()
    expressions: set[str] = set()
    source_id = ""
    frame_rate = 0.0
    carries_confidence = False
    for line in text.splitlines():
        tokens = line.split()
        if not tokens:
            continue
        if tokens[0] == "sourceId":
            source_id = tokens[1]
        elif tokens[0] == "frameRate":
            frame_rate = float(tokens[1])
        elif tokens[0] == "t":
            timestamps.append(float(tokens[1]))
        elif tokens[0] == "b":
            bones.add(tokens[1])
            carries_confidence = carries_confidence or len(tokens) > 6
        elif tokens[0] == "e":
            expressions.add(tokens[1])

    data = text.encode("utf-8")
    return {
        "sourceId": source_id,
        "frames": len(timestamps),
        "durationSeconds": round(timestamps[-1] - timestamps[0], 6),
        "nominalFrameRate": frame_rate,
        "observedBones": len(bones),
        "bones": sorted(bones),
        "carriesConfidence": carries_confidence,
        # The union across the clip, so a name only some frames report is still
        # listed -- which is the whole point of the expressions fixture.
        "observedExpressions": len(expressions),
        "expressions": sorted(expressions),
        "sha256": hashlib.sha256(data).hexdigest(),
        "bytes": len(data),
    }


def field_matches(claimed, measured) -> bool:
    if isinstance(measured, float) or isinstance(claimed, float):
        try:
            return abs(float(claimed) - float(measured)) <= 1e-6
        except (TypeError, ValueError):
            return False
    return claimed == measured


def sync_manifest(directory: pathlib.Path, rendered: dict[str, str],
                  check: bool) -> list[str]:
    """Compare (or rewrite) the manifest's measured fields. Returns problems."""
    path = directory / MANIFEST_NAME
    if not path.exists():
        return [f"{MANIFEST_NAME} is missing"]

    manifest = json.loads(path.read_text(encoding="utf-8"))
    problems: list[str] = []

    if manifest.get("format", {}).get("version") != TRACE_FORMAT_VERSION:
        problems.append(
            f"{MANIFEST_NAME}: format.version is "
            f"{manifest.get('format', {}).get('version')!r}, expected "
            f"{TRACE_FORMAT_VERSION}")
        if not check:
            manifest.setdefault("format", {})["version"] = TRACE_FORMAT_VERSION

    listed = [entry.get("file") for entry in manifest.get("traces", [])]
    if sorted(listed) != sorted(rendered):
        problems.append(
            f"{MANIFEST_NAME} describes {sorted(listed)}, the corpus is "
            f"{sorted(rendered)}")
        return problems

    for entry in manifest["traces"]:
        derived = {"id": pathlib.Path(entry["file"]).stem,
                   **measure(rendered[entry["file"]])}
        for key, value in derived.items():
            if not field_matches(entry.get(key), value):
                problems.append(
                    f"{entry['file']}: {key} is {entry.get(key)!r}, measured "
                    f"{value!r}")
        if not check:
            entry.update(derived)

    if check:
        return problems

    # Writing mode fills the derived fields in, so a new entry needs only its
    # `file` and the prose no tool can infer. Report what changed either way:
    # silently rewriting a provenance record is the wrong kind of convenient.
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8", newline="\n")
    for problem in problems:
        print(f"updated {problem}")
    return []


def main() -> int:
    default_output = pathlib.Path(__file__).resolve().parents[1] / "tests" / "corpus"
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, default=default_output,
                        help="corpus directory to write into")
    parser.add_argument("--check", action="store_true",
                        help="fail if any committed trace differs from the "
                             "freshly generated one instead of rewriting it")
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    drifted: list[str] = []
    rendered: dict[str, str] = {}
    for name, builder in sorted(TRACES.items()):
        text = builder()
        rendered[name] = text
        path = args.output / name
        existing = (path.read_text(encoding="utf-8", newline="")
                    if path.exists() else None)
        if args.check:
            if existing != text:
                drifted.append(name)
            continue
        # Binary-mode newline control: a trace written on Windows must equal one
        # written on Linux, or the three OS cells cannot share the fixture.
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        print(f"wrote {path.relative_to(args.output.parent.parent.parent)}"
              f" ({text.count(chr(10))} lines)")

    if drifted:
        print("regenerated traces differ from the committed corpus: "
              + ", ".join(drifted), file=sys.stderr)
        print("run: python libs/motionRuntime/tools/generate_traces.py",
              file=sys.stderr)
        return 1

    problems = sync_manifest(args.output, rendered, args.check)
    if problems:
        for problem in problems:
            print(f"manifest drift: {problem}", file=sys.stderr)
        print("run: python libs/motionRuntime/tools/generate_traces.py",
              file=sys.stderr)
        return 1
    if not args.check:
        print(f"{MANIFEST_NAME} is in sync with {len(rendered)} trace(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
