# SPDX-License-Identifier: Apache-2.0
"""End-to-end smoke tests for the usdVrm file-format plugin.

Drives the freshly built plugin through OpenUSD's Python bindings: opens each
committed .vrm fixture as a stage and asserts the import contract. Fixtures are
generated by tools/generate_fixtures.py.

The build wires PXR_PLUGINPATH_NAME / PATH / PYTHONPATH (see CMakeLists.txt);
when run by hand, do it inside `ost plugin run plugins/usdVrm -- python ...`.
"""
import os
import pathlib
import sys

from pxr import Gf, Plug, Sdf, Usd, UsdGeom, UsdShade, UsdSkel

FIXTURES = pathlib.Path(__file__).parent / "fixtures"


def _open(name):
    stage = Usd.Stage.Open(str(FIXTURES / name))
    assert stage, f"failed to open {name}"
    return stage


def check_minimal():
    """Skinned mesh + non-skinned node-placed accessory; IBM bind; humanoid."""
    stage = _open("minimal.vrm")

    dp = stage.GetDefaultPrim()
    assert dp and dp.GetPath().pathString == "/Asset", dp
    assert dp.GetTypeName() == "SkelRoot", dp.GetTypeName()
    assert abs(UsdGeom.GetStageMetersPerUnit(stage) - 1.0) < 1e-9
    assert UsdGeom.GetStageUpAxis(stage) == UsdGeom.Tokens.y

    vrm = dp.GetCustomData().get("vrm", {})
    assert vrm.get("sourceFormat") == "VRM", vrm
    assert vrm.get("specVersion") == "1.0", vrm
    assert vrm.get("meta"), "VRM meta should be preserved on /Asset"
    assert vrm.get("rawExtension"), "VRM rawExtension should be preserved"
    assert "humanoid" in vrm["rawExtension"], "rawExtension should be the VRM block"

    body = stage.GetPrimAtPath("/Asset/geo/Body")
    assert body and body.IsA(UsdGeom.Mesh), "expected /Asset/geo/Body mesh"
    binding = UsdSkel.BindingAPI(body)
    assert binding.GetSkeletonRel().GetTargets() == [Sdf.Path("/Asset/skel/Skeleton")]
    assert binding.GetJointWeightsPrimvar().Get(), "missing joint weights"
    # Skinned verts live in skel-root space (glTF ignores the mesh node
    # transform), so the geom bind transform must be identity.
    assert binding.GetGeomBindTransformAttr().Get() == Gf.Matrix4d(1.0)

    mat_rel = UsdShade.MaterialBindingAPI(body).GetDirectBindingRel()
    assert mat_rel.GetTargets() == [Sdf.Path("/Asset/mtl/Body_Mat")], mat_rel.GetTargets()

    # P0.2: the non-skinned Accessory keeps its glTF node placement (x = 1.0).
    acc = stage.GetPrimAtPath("/Asset/geo/Accessory")
    assert acc and acc.IsA(UsdGeom.Mesh), "expected /Asset/geo/Accessory mesh"
    assert not UsdSkel.BindingAPI(acc).GetSkeletonRel().GetTargets()
    xf = acc.GetAttribute("xformOp:transform").Get()
    assert xf is not None and abs(xf.ExtractTranslation()[0] - 1.0) < 1e-6, \
        f"Accessory node transform lost: {xf}"

    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    assert list(skel.GetJointsAttr().Get()) == ["hips", "hips/spine"]
    # P0.1: bind from the (identity) inverse binds, not the non-identity node
    # world transforms.
    binds = skel.GetBindTransformsAttr().Get()
    assert binds and all(b == Gf.Matrix4d(1.0) for b in binds), list(binds)
    assert abs(skel.GetRestTransformsAttr().Get()[0].ExtractTranslation()[1] - 0.5) < 1e-6

    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    assert humanoid.IsValid()
    assert humanoid.GetRelationship("vrm:skeleton").GetTargets() == \
        [Sdf.Path("/Asset/skel/Skeleton")]
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"
    assert humanoid.GetAttribute("vrm:humanBones:spine").Get() == "hips/spine"


def check_vrm0():
    """The VRM 0.x extension shape (extensions.VRM, humanBones as an array)."""
    stage = _open("vrm0_minimal.vrm")
    vrm = stage.GetDefaultPrim().GetCustomData().get("vrm", {})
    assert vrm.get("sourceVersion") == "0.x", vrm
    assert vrm.get("meta"), "VRM 0.x meta should be preserved"
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    assert list(skel.GetJointsAttr().Get()) == ["hips", "hips/spine"]
    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"


def check_multiskin_ibm():
    """Two skins unify into one skeleton; bind transforms come from the IBMs."""
    stage = _open("multiskin_ibm.vrm")
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    joints = list(skel.GetJointsAttr().Get())
    assert joints == ["hips", "hips/spine", "hips/spine/extra"], joints
    binds = skel.GetBindTransformsAttr().Get()
    ys = [b.ExtractTranslation()[1] for b in binds]
    assert all(abs(a - b) < 1e-6 for a, b in zip(ys, [0.5, 0.8, 1.0])), ys
    # Both meshes are skinned and bound to the one skeleton.
    for name in ("BodyA", "BodyB"):
        m = stage.GetPrimAtPath(f"/Asset/geo/{name}")
        assert UsdSkel.BindingAPI(m).GetSkeletonRel().GetTargets() == \
            [Sdf.Path("/Asset/skel/Skeleton")], name
    # BodyB's local skin joint 0 (spine) must remap to the unified index 1.
    jiB = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/geo/BodyB")).GetJointIndicesPrimvar().Get()
    assert jiB[0] == 1, f"BodyB joint index not remapped to unified order: {jiB[0]}"


def check_unordered_skel():
    """A child-before-parent skin must be reordered to a valid UsdSkel topology."""
    stage = _open("unordered_skel.vrm")
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    joints = list(skel.GetJointsAttr().Get())
    assert joints == ["hips", "hips/spine"], joints
    valid, reason = UsdSkel.Topology(joints).Validate()
    assert valid, f"invalid skeleton topology: {reason}"
    # Verts were weighted to the skin's local joint 0 (spine); after reorder +
    # remap that must point at the unified spine index (1).
    ji = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/geo/Body")).GetJointIndicesPrimvar().Get()
    assert ji[0] == 1, f"joint index not remapped after topo reorder: {ji[0]}"


def check_names():
    """Duplicate / Japanese / empty names sanitize+uniquify without collisions."""
    stage = _open("names.vrm")
    geo = stage.GetPrimAtPath("/Asset/geo")
    meshes = [p for p in geo.GetChildren() if p.IsA(UsdGeom.Mesh)]
    names = [p.GetName() for p in meshes]
    assert len(names) == 4, names
    assert len(set(names)) == 4, f"name collision: {names}"
    for n in names:
        assert n and (n[0].isalpha() or n[0] == "_"), f"invalid identifier: {n}"
    mats = stage.GetPrimAtPath("/Asset/mtl").GetChildren()
    assert len({m.GetName() for m in mats}) == 2, [m.GetName() for m in mats]


def check_materials():
    """Alpha BLEND/opacity and alpha MASK -> opacityThreshold."""
    stage = _open("materials.vrm")
    leaf = stage.GetPrimAtPath("/Asset/mtl/Leaf/Surface")
    assert leaf.IsValid(), "expected MASK material Leaf"
    thr = leaf.GetAttribute("inputs:opacityThreshold").Get()
    assert thr is not None and abs(thr - 0.3) < 1e-6, f"MASK opacityThreshold: {thr}"
    glass = stage.GetPrimAtPath("/Asset/mtl/Glass/Surface")
    assert abs(glass.GetAttribute("inputs:opacity").Get() - 0.3) < 1e-6


def check_badext():
    """A semantically broken VRM humanoid must warn+skip, never crash."""
    stage = _open("badext.vrm")
    assert stage.GetPrimAtPath("/Asset").IsValid()
    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    # The valid bone maps; the out-of-range one is dropped.
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"
    assert not humanoid.GetAttribute("vrm:humanBones:spine").IsValid(), \
        "out-of-range humanoid bone should be skipped"
    # The raw block is still preserved even though parts were unusable.
    assert stage.GetDefaultPrim().GetCustomData().get("vrm", {}).get("rawExtension")


def main() -> int:
    plugin_path = os.environ.get("PXR_PLUGINPATH_NAME")
    if plugin_path:
        Plug.Registry().RegisterPlugins(plugin_path.split(os.pathsep))
    assert Sdf.FileFormat.FindByExtension("vrm"), \
        "usdVrm SdfFileFormat is not registered"

    for check in (check_minimal, check_vrm0, check_multiskin_ibm,
                  check_unordered_skel, check_names, check_materials, check_badext):
        check()
        print(f"  {check.__name__}: OK")
    print("usdVrm smoke tests: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
