# SPDX-License-Identifier: Apache-2.0
"""End-to-end smoke tests for the usdVrm file-format plugin.

Drives the freshly built plugin through OpenUSD's Python bindings: opens each
committed .vrm fixture as a stage and asserts the import contract. Fixtures are
generated by tools/generate_fixtures.py.

The build wires PXR_PLUGINPATH_NAME / PATH / PYTHONPATH (see CMakeLists.txt);
when run by hand, do it inside `ost plugin run plugins/usdVrm -- python ...`.
"""
import os
import pathlib
import sys
import tempfile

from pxr import Ar, Gf, Plug, Sdf, Usd, UsdGeom, UsdShade, UsdSkel, Vt

FIXTURES = pathlib.Path(__file__).parent / "fixtures"
TOOLS = pathlib.Path(__file__).parents[1] / "tools"
sys.path.insert(0, str(TOOLS))

from package_vrm import package_stage


def _open(name):
    stage = Usd.Stage.Open(str(FIXTURES / name))
    assert stage, f"failed to open {name}"
    return stage


def _vclose(a, b, eps=1e-5):
    return all(abs(a[i] - b[i]) < eps for i in range(len(a)))


def check_minimal():
    """Skinned mesh + non-skinned node-placed accessory; IBM bind; humanoid."""
    stage = _open("minimal.vrm")

    dp = stage.GetDefaultPrim()
    assert dp and dp.GetPath().pathString == "/Asset", dp
    assert dp.GetTypeName() == "SkelRoot", dp.GetTypeName()
    assert abs(UsdGeom.GetStageMetersPerUnit(stage) - 1.0) < 1e-9
    assert UsdGeom.GetStageUpAxis(stage) == UsdGeom.Tokens.y

    vrm = dp.GetCustomData().get("vrm", {})
    assert vrm.get("sourceFormat") == "VRM", vrm
    assert vrm.get("specVersion") == "1.0", vrm
    assert vrm.get("meta"), "VRM meta should be preserved on /Asset"
    assert vrm.get("rawExtension"), "VRM rawExtension should be preserved"
    assert "humanoid" in vrm["rawExtension"], "rawExtension should be the VRM block"
    # VRM 1.0 already faces +Z: no front-normalization rotation.
    assert vrm.get("sourceFrontAxis") == "+Z", vrm
    assert vrm.get("frontAxisNormalized") is False, vrm
    assert not dp.GetAttribute("xformOp:rotateY").IsValid(), "VRM 1.0 must not be rotated"

    body = stage.GetPrimAtPath("/Asset/geo/Body")
    assert body and body.IsA(UsdGeom.Mesh), "expected /Asset/geo/Body mesh"
    binding = UsdSkel.BindingAPI(body)
    assert binding.GetSkeletonRel().GetTargets() == [Sdf.Path("/Asset/skel/Skeleton")]
    assert binding.GetJointWeightsPrimvar().Get(), "missing joint weights"
    # Skinned verts live in skel-root space (glTF ignores the mesh node
    # transform), so the geom bind transform must be identity.
    assert binding.GetGeomBindTransformAttr().Get() == Gf.Matrix4d(1.0)

    mat_rel = UsdShade.MaterialBindingAPI(body).GetDirectBindingRel()
    assert mat_rel.GetTargets() == [Sdf.Path("/Asset/mtl/Body_Mat")], mat_rel.GetTargets()

    # P0.2: the non-skinned Accessory keeps its glTF node placement (x = 1.0).
    acc = stage.GetPrimAtPath("/Asset/geo/Accessory")
    assert acc and acc.IsA(UsdGeom.Mesh), "expected /Asset/geo/Accessory mesh"
    assert not UsdSkel.BindingAPI(acc).GetSkeletonRel().GetTargets()
    xf = acc.GetAttribute("xformOp:transform").Get()
    assert xf is not None and abs(xf.ExtractTranslation()[0] - 1.0) < 1e-6, \
        f"Accessory node transform lost: {xf}"

    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    assert list(skel.GetJointsAttr().Get()) == ["hips", "hips/spine"]
    # P0.1: bind from the (identity) inverse binds, not the non-identity node
    # world transforms.
    binds = skel.GetBindTransformsAttr().Get()
    assert binds and all(b == Gf.Matrix4d(1.0) for b in binds), list(binds)
    assert abs(skel.GetRestTransformsAttr().Get()[0].ExtractTranslation()[1] - 0.5) < 1e-6

    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    assert humanoid.IsValid()
    assert humanoid.GetRelationship("vrm:skeleton").GetTargets() == \
        [Sdf.Path("/Asset/skel/Skeleton")]
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"
    assert humanoid.GetAttribute("vrm:humanBones:spine").Get() == "hips/spine"

    # Phase 4: the typed VrmHumanoidAPI (compiled into this plugin) is registered
    # and applied, and the standard bones are schema builtins, not custom attrs.
    assert Usd.SchemaRegistry().IsAppliedAPISchema("VrmHumanoidAPI"), \
        "VrmHumanoidAPI not registered — check plugInfo Types + generatedSchema.usda"
    assert "VrmHumanoidAPI" in humanoid.GetAppliedSchemas(), \
        humanoid.GetAppliedSchemas()
    assert humanoid.GetAttribute("vrm:humanBones:hips").IsCustom() is False, \
        "a standard VRM bone should be a schema builtin, not a custom attribute"


def check_vrm0():
    """The VRM 0.x extension shape (extensions.VRM, humanBones as an array)."""
    stage = _open("vrm0_minimal.vrm")
    dp = stage.GetDefaultPrim()
    vrm = dp.GetCustomData().get("vrm", {})
    assert vrm.get("sourceVersion") == "0.x", vrm
    assert vrm.get("meta"), "VRM 0.x meta should be preserved"
    # Front normalization is baked into the data (no root xformOp). The detailed
    # bake assertions live in check_vrm0_frontbake; here just confirm the policy.
    assert vrm.get("sourceFrontAxis") == "-Z", vrm
    assert vrm.get("frontAxisNormalized") is True, vrm
    assert not dp.GetAttribute("xformOp:rotateY").IsValid(), \
        "VRM 0.x must bake the front rotation, not rotate the root"
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    assert list(skel.GetJointsAttr().Get()) == ["hips", "hips/spine"]
    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"


def check_multiskin_ibm():
    """Two skins unify into one skeleton; bind transforms come from the IBMs."""
    stage = _open("multiskin_ibm.vrm")
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    joints = list(skel.GetJointsAttr().Get())
    assert joints == ["hips", "hips/spine", "hips/spine/extra"], joints
    binds = skel.GetBindTransformsAttr().Get()
    ys = [b.ExtractTranslation()[1] for b in binds]
    assert all(abs(a - b) < 1e-6 for a, b in zip(ys, [0.5, 0.8, 1.0])), ys
    # Both meshes are skinned and bound to the one skeleton.
    for name in ("BodyA", "BodyB"):
        m = stage.GetPrimAtPath(f"/Asset/geo/{name}")
        assert UsdSkel.BindingAPI(m).GetSkeletonRel().GetTargets() == \
            [Sdf.Path("/Asset/skel/Skeleton")], name
    # BodyB's local skin joint 0 (spine) must remap to the unified index 1.
    jiB = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/geo/BodyB")).GetJointIndicesPrimvar().Get()
    assert jiB[0] == 1, f"BodyB joint index not remapped to unified order: {jiB[0]}"


def check_unordered_skel():
    """A child-before-parent skin must be reordered to a valid UsdSkel topology."""
    stage = _open("unordered_skel.vrm")
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    joints = list(skel.GetJointsAttr().Get())
    assert joints == ["hips", "hips/spine"], joints
    valid, reason = UsdSkel.Topology(joints).Validate()
    assert valid, f"invalid skeleton topology: {reason}"
    # Verts were weighted to the skin's local joint 0 (spine); after reorder +
    # remap that must point at the unified spine index (1).
    ji = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/geo/Body")).GetJointIndicesPrimvar().Get()
    assert ji[0] == 1, f"joint index not remapped after topo reorder: {ji[0]}"


def check_expressions():
    """Morph target -> UsdSkelBlendShape, bound on the mesh + an expression."""
    stage = _open("expressions.vrm")

    # Blend shape authored under /Asset/skel/BlendShapes with the right offsets.
    bs_scope = stage.GetPrimAtPath("/Asset/skel/BlendShapes")
    assert bs_scope.IsValid(), "expected /Asset/skel/BlendShapes"
    bs = [p for p in bs_scope.GetChildren() if p.IsA(UsdSkel.BlendShape)]
    assert len(bs) == 1, bs
    offsets = UsdSkel.BlendShape(bs[0]).GetOffsetsAttr().Get()
    assert len(offsets) == 3 and abs(offsets[2][1] - 0.5) < 1e-6, list(offsets)

    # Mesh binding references the blend shape.
    face = UsdSkel.BindingAPI(stage.GetPrimAtPath("/Asset/geo/Face"))
    assert face.GetBlendShapesAttr().Get(), "mesh missing skel:blendShapes"
    assert face.GetBlendShapeTargetsRel().GetTargets() == [bs[0].GetPath()]

    # Expression binds the morph target with weight 1.0.
    happy = stage.GetPrimAtPath("/Asset/rig/Expressions/happy")
    assert happy.IsValid(), "expected /Asset/rig/Expressions/happy"
    assert "VrmExpressionAPI" in happy.GetAppliedSchemas(), happy.GetAppliedSchemas()
    assert happy.GetAttribute("vrm:expressionType").Get() == "preset"
    assert happy.GetAttribute("vrm:expressionType").IsCustom() is False
    targets = happy.GetRelationship("vrm:morphTargets").GetTargets()
    assert targets == [bs[0].GetPath()], targets
    weights = happy.GetAttribute("vrm:morphTargetWeights").Get()
    assert weights and abs(weights[0] - 1.0) < 1e-6, list(weights)

    # materialColorBinds: drives Face_Mat emission to red.
    ct = happy.GetRelationship("vrm:materialColorTargets").GetTargets()
    assert ct == [Sdf.Path("/Asset/mtl/Face_Mat")], ct
    assert list(happy.GetAttribute("vrm:materialColorTypes").Get()) == ["emissionColor"]
    cv = happy.GetAttribute("vrm:materialColorValues").Get()
    assert cv and tuple(cv[0]) == (1.0, 0.0, 0.0, 1.0), list(cv)


def check_vrm0_expressions():
    """VRM 0.x blendShapeMaster: preset detection + weight 0..100 -> 0..1."""
    stage = _open("vrm0_expressions.vrm")

    bs_scope = stage.GetPrimAtPath("/Asset/skel/BlendShapes")
    assert bs_scope.IsValid(), "expected /Asset/skel/BlendShapes"
    bs = [p for p in bs_scope.GetChildren() if p.IsA(UsdSkel.BlendShape)]
    assert len(bs) == 1, bs

    # The morph mesh carries a skel:skeleton binding (needed to drive the blend
    # shapes), plus the blend-shape binding.
    face = UsdSkel.BindingAPI(stage.GetPrimAtPath("/Asset/geo/Face"))
    assert face.GetSkeletonRel().GetTargets() == ["/Asset/skel/Skeleton"]
    assert face.GetBlendShapeTargetsRel().GetTargets() == [bs[0].GetPath()]

    # presetName "joy" -> preset; weight 100 normalizes to 1.0.
    joy = stage.GetPrimAtPath("/Asset/rig/Expressions/joy")
    assert joy.IsValid(), "expected /Asset/rig/Expressions/joy"
    assert joy.GetAttribute("vrm:expressionType").Get() == "preset"
    assert joy.GetRelationship("vrm:morphTargets").GetTargets() == [bs[0].GetPath()]
    weights = joy.GetAttribute("vrm:morphTargetWeights").Get()
    assert weights and abs(weights[0] - 1.0) < 1e-6, list(weights)


def check_names():
    """Duplicate / Japanese / empty names sanitize+uniquify without collisions."""
    stage = _open("names.vrm")
    geo = stage.GetPrimAtPath("/Asset/geo")
    meshes = [p for p in geo.GetChildren() if p.IsA(UsdGeom.Mesh)]
    names = [p.GetName() for p in meshes]
    assert len(names) == 4, names
    assert len(set(names)) == 4, f"name collision: {names}"
    for n in names:
        assert n and (n[0].isalpha() or n[0] == "_"), f"invalid identifier: {n}"
    mats = stage.GetPrimAtPath("/Asset/mtl").GetChildren()
    assert len({m.GetName() for m in mats}) == 2, [m.GetName() for m in mats]


def check_materials():
    """Alpha BLEND/opacity and alpha MASK -> opacityThreshold."""
    stage = _open("materials.vrm")
    leaf = stage.GetPrimAtPath("/Asset/mtl/Leaf/Surface")
    assert leaf.IsValid(), "expected MASK material Leaf"
    thr = leaf.GetAttribute("inputs:opacityThreshold").Get()
    assert thr is not None and abs(thr - 0.3) < 1e-6, f"MASK opacityThreshold: {thr}"
    glass = stage.GetPrimAtPath("/Asset/mtl/Glass/Surface")
    assert abs(glass.GetAttribute("inputs:opacity").Get() - 0.3) < 1e-6
    # KHR_materials_unlit: base color via emissive, diffuse/lit response killed,
    # so scene lights don't facet the low-poly surface.
    flat = stage.GetPrimAtPath("/Asset/mtl/Unlit/Surface")
    assert flat.IsValid(), "expected unlit material Unlit"
    assert flat.GetAttribute("inputs:diffuseColor").Get() == Gf.Vec3f(0, 0, 0)
    em = flat.GetAttribute("inputs:emissiveColor").Get()
    assert abs(em[0] - 0.9) < 1e-6 and abs(em[2] - 0.1) < 1e-6, em
    assert abs(flat.GetAttribute("inputs:metallic").Get()) < 1e-6


def check_springbone():
    """VRM SpringBone -> /Asset/rig/SecondaryMotion (chains + colliders, data)."""
    stage = _open("springbone.vrm")
    sm = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion")
    assert sm.IsValid(), "expected /Asset/rig/SecondaryMotion"
    assert sm.GetCustomData().get("vrm", {}).get("springBone", {}).get("raw")

    hair = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion/SpringBones/Hair")
    assert hair.IsValid(), "expected SpringBones/Hair"
    assert "VrmSpringBoneAPI" in hair.GetAppliedSchemas(), hair.GetAppliedSchemas()
    assert list(hair.GetAttribute("vrm:joints").Get()) == \
        ["hips/spine/hair1", "hips/spine/hair1/hair2"]
    stiff = list(hair.GetAttribute("vrm:stiffness").Get())
    assert abs(stiff[0] - 1.0) < 1e-6 and abs(stiff[1] - 0.8) < 1e-6, stiff
    assert abs(hair.GetAttribute("vrm:gravityPower").Get()[0] - 0.5) < 1e-6
    assert hair.GetAttribute("vrm:center").Get() == "springCenter"

    head = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion/Colliders/Head")
    assert head.IsValid(), "expected Colliders/Head"
    assert hair.GetRelationship("vrm:colliderGroups").GetTargets() == [head.GetPath()]
    col = stage.GetPrimAtPath(
        "/Asset/rig/SecondaryMotion/Colliders/Head/Collider_0")
    assert "VrmColliderAPI" in col.GetAppliedSchemas(), col.GetAppliedSchemas()
    assert col.GetAttribute("vrm:shape").Get() == "sphere"
    assert abs(col.GetAttribute("vrm:radius").Get() - 0.1) < 1e-6
    assert col.GetAttribute("vrm:node").Get() == "hips/spine"


def check_shared_accessor():
    """Two primitives sharing one accessor are compacted to their used verts."""
    stage = _open("shared_accessor.vrm")
    for name in ("Quad_0", "Quad_1"):
        m = UsdGeom.Mesh(stage.GetPrimAtPath(f"/Asset/geo/{name}"))
        assert m, name
        pts = m.GetPointsAttr().Get()
        fvi = m.GetFaceVertexIndicesAttr().Get()
        # Compacted: exactly the 3 referenced verts, topology covering them all.
        assert len(pts) == 3, (name, len(pts))
        assert max(fvi) == len(pts) - 1, (name, list(fvi), len(pts))


def check_animation():
    """A glTF rotation clip -> UsdSkelAnimation bound to the skeleton."""
    stage = _open("animation.vrm")
    anim = UsdSkel.Animation(stage.GetPrimAtPath("/Asset/skel/Animations/wave"))
    assert anim, "expected /Asset/skel/Animations/wave"
    assert list(anim.GetJointsAttr().Get()) == ["hips/spine"]

    rattr = anim.GetRotationsAttr()
    ts = rattr.GetTimeSamples()
    assert ts and abs(ts[0] - 0.0) < 1e-6 and abs(ts[-1] - 30.0) < 1e-6, ts
    q0 = rattr.Get(0.0)[0]
    assert abs(q0.GetReal() - 1.0) < 1e-4, q0          # identity at t=0
    qn = rattr.Get(30.0)[0]
    assert abs(qn.GetReal() - 0.7071) < 1e-3, qn       # 90 deg about Z at t=1s
    assert abs(qn.GetImaginary()[2] - 0.7071) < 1e-3, qn

    # Bound so it plays, with the stage time range set.
    src = UsdSkel.BindingAPI(
        stage.GetPrimAtPath("/Asset/skel/Skeleton")).GetAnimationSourceRel()
    assert src.GetTargets() == [Sdf.Path("/Asset/skel/Animations/wave")], src.GetTargets()
    assert abs(stage.GetStartTimeCode() - 0.0) < 1e-6
    assert abs(stage.GetEndTimeCode() - 30.0) < 1e-6


def check_lookat():
    """VRM lookAt -> /Asset/rig/LookAt with eye tokens + preserved curves."""
    stage = _open("lookat.vrm")
    la = stage.GetPrimAtPath("/Asset/rig/LookAt")
    assert la.IsValid(), "expected /Asset/rig/LookAt"
    assert "VrmLookAtAPI" in la.GetAppliedSchemas(), la.GetAppliedSchemas()
    assert la.GetAttribute("vrm:type").Get() == "bone"
    assert la.GetAttribute("vrm:leftEye").Get() == "hips/spine/head/leftEye"
    assert la.GetAttribute("vrm:rightEye").Get() == "hips/spine/head/rightEye"
    assert la.GetRelationship("vrm:skeleton").GetTargets() == \
        [Sdf.Path("/Asset/skel/Skeleton")]
    raw = la.GetCustomData().get("vrm", {}).get("lookAt", {}).get("raw")
    assert raw and "rangeMapHorizontalInner" in raw, "lookAt curves not preserved"


def check_textures():
    """Embedded base-color texture -> UsdUVTexture + st reader; MToon metadata."""
    stage = _open("textures.vrm")
    mat = stage.GetPrimAtPath("/Asset/mtl/Skin")
    surf = stage.GetPrimAtPath("/Asset/mtl/Skin/Surface")
    tex = stage.GetPrimAtPath("/Asset/mtl/Skin/baseColorTexture")
    assert mat.IsValid() and surf.IsValid() and tex.IsValid()

    assert tex.GetAttribute("info:id").Get() == "UsdUVTexture"
    f = tex.GetAttribute("inputs:file").Get()
    assert f and ".vrm[" in f.path and f.path.endswith(".png]"), f
    resolved = Ar.GetResolver().Resolve(f.path)
    assert resolved, f
    asset = Ar.GetResolver().OpenAsset(resolvedPath=resolved)
    assert asset and asset.GetSize() > 0, f
    assert tex.GetAttribute("inputs:sourceColorSpace").Get() == "sRGB"
    assert tex.GetAttribute("inputs:wrapS").Get() == "repeat"
    assert tex.GetAttribute("inputs:wrapT").Get() == "clamp"

    # diffuseColor <- texture.rgb, and st <- stReader.result.
    conn = surf.GetAttribute("inputs:diffuseColor").GetConnections()
    assert conn == [Sdf.Path("/Asset/mtl/Skin/baseColorTexture.outputs:rgb")], conn
    assert stage.GetPrimAtPath("/Asset/mtl/Skin/stReader").IsValid()
    stc = tex.GetAttribute("inputs:st").GetConnections()
    assert stc == [Sdf.Path("/Asset/mtl/Skin/stReader.outputs:result")], stc

    # MToon preserved as metadata.
    assert mat.GetAttribute("vrm:shaderModel").Get() == "MToon"
    assert mat.GetCustomData().get("vrm", {}).get("mtoon", {}).get("raw")


def check_portable_package():
    """Package command copies temp-cache textures and rewrites paths relative."""
    with tempfile.TemporaryDirectory() as tmp:
        package_dir = pathlib.Path(tmp) / "textures_package"
        report = package_stage(FIXTURES / "textures.vrm", package_dir)

        assert report["summary"]["texturesPackaged"] == 1, report
        assert report["summary"]["missingAssets"] == 0, report
        assert report["pathPolicy"]["textureAssetPaths"] == "relative-to-package-root"

        stage_path = package_dir / report["stage"]
        report_path = package_dir / "package_report.json"
        assert stage_path.exists(), stage_path
        assert report_path.exists(), report_path

        packaged_stage = Usd.Stage.Open(str(stage_path))
        assert packaged_stage, f"failed to open packaged stage: {stage_path}"
        tex = packaged_stage.GetPrimAtPath("/Asset/mtl/Skin/baseColorTexture")
        asset = tex.GetAttribute("inputs:file").Get()
        assert asset.path.startswith("textures/"), asset
        assert not pathlib.Path(asset.path).is_absolute(), asset
        assert (package_dir / asset.path).exists(), asset

        entry = report["assets"][0]
        assert entry["status"] == "packaged", entry
        assert entry["portablePath"] == asset.path, entry
        assert len(entry["sha256"]) == 64, entry


def check_vrm0_frontbake():
    """VRM 0.x front bake: 180-about-Y baked into data, not a root xformOp."""
    stage = _open("vrm0_frontbake.vrm")
    dp = stage.GetDefaultPrim()
    assert not dp.GetAttribute("xformOp:rotateY").IsValid(), "must bake, not rotate root"
    assert dp.GetCustomData().get("vrm", {}).get("frontAxisNormalized") is True

    # Skinned mesh points rotated 180 about Y: (x,y,z) -> (-x,y,-z).
    body = UsdGeom.Mesh(stage.GetPrimAtPath("/Asset/geo/Body"))
    pts = body.GetPointsAttr().Get()
    assert _vclose(pts[0], (0.5, 0.0, -1.0)), list(pts)
    assert _vclose(pts[2], (0.0, 1.0, -1.0)), list(pts)

    # Root (hips) rest carries the rotation (+ keeps its translation); bind too.
    skel = UsdSkel.Skeleton(stage.GetPrimAtPath("/Asset/skel/Skeleton"))
    rest0 = skel.GetRestTransformsAttr().Get()[0]
    assert _vclose(rest0.TransformDir(Gf.Vec3d(1, 0, 0)), (-1, 0, 0)), rest0
    assert _vclose(rest0.ExtractTranslation(), (0, 0.5, 0)), rest0
    bind0 = skel.GetBindTransformsAttr().Get()[0]
    assert _vclose(bind0.TransformDir(Gf.Vec3d(0, 0, 1)), (0, 0, -1)), bind0

    # Embedded clip's root (hips) track is baked: rotation 90 -> 90+180 = 270 deg
    # about Y, translation (1,0.5,0) -> (-1,0.5,0).
    anim = UsdSkel.Animation(stage.GetPrimAtPath("/Asset/skel/Animations/move"))
    assert list(anim.GetJointsAttr().Get()) == ["hips"]
    t1 = anim.GetTranslationsAttr().Get(30.0)[0]
    assert _vclose(t1, (-1.0, 0.5, 0.0)), t1
    q = anim.GetRotationsAttr().Get(30.0)[0]
    qm = Gf.Matrix3d(Gf.Quatd(q.GetReal(), Gf.Vec3d(*q.GetImaginary())))
    exp = Gf.Matrix3d(Gf.Rotation(Gf.Vec3d(0, 1, 0), 270.0))
    assert _vclose(Gf.Vec3d(1, 0, 0) * qm, Gf.Vec3d(1, 0, 0) * exp), q

    # Skinning still reproduces the (rotated) source at the rest pose (t=0): the
    # bake is internally consistent across points + bind + rest + the bound clip.
    cache = UsdSkel.Cache()
    cache.Populate(UsdSkel.Root(dp), Usd.PrimDefaultPredicate)
    skelQ = cache.GetSkelQuery(skel)
    skinQ = cache.GetSkinningQuery(body.GetPrim())
    xforms = skelQ.ComputeSkinningTransforms(Usd.TimeCode(0.0))
    skinned = Vt.Vec3fArray(list(pts))
    assert skinQ.ComputeSkinnedPoints(xforms, skinned, Usd.TimeCode(0.0))
    for i in range(len(pts)):
        assert _vclose(skinned[i], pts[i], 1e-4), (i, skinned[i], pts[i])

    # Spring gravityDir is a model-space direction, so it's baked too:
    # the "wind" (1,0,0) becomes (-1,0,0) for the now-+Z avatar.
    spring = stage.GetPrimAtPath("/Asset/rig/SecondaryMotion/SpringBones/Wind")
    assert spring.IsValid(), "expected baked spring at .../SpringBones/Wind"
    gdir = spring.GetAttribute("vrm:gravityDir").Get()
    assert gdir and _vclose(gdir[0], (-1.0, 0.0, 0.0)), list(gdir)


def check_constraints():
    """VRMC_node_constraint -> /Asset/rig/Constraints (type/source/axis/weight)."""
    stage = _open("constraints.vrm")
    con = stage.GetPrimAtPath("/Asset/rig/Constraints/head_roll")
    assert con.IsValid(), "expected /Asset/rig/Constraints/head_roll"
    assert "VrmConstraintAPI" in con.GetAppliedSchemas(), con.GetAppliedSchemas()
    assert con.GetAttribute("vrm:type").Get() == "roll"
    assert con.GetAttribute("vrm:constrained").Get() == "hips/spine/head"
    assert con.GetAttribute("vrm:source").Get() == "hips/spine"
    assert con.GetAttribute("vrm:axis").Get() == "X"
    assert abs(con.GetAttribute("vrm:weight").Get() - 0.8) < 1e-6
    raw = con.GetCustomData().get("vrm", {}).get("constraint", {}).get("raw")
    assert raw and "rollAxis" in raw, "constraint raw block not preserved"


def check_badext():
    """A semantically broken VRM humanoid must warn+skip, never crash."""
    stage = _open("badext.vrm")
    assert stage.GetPrimAtPath("/Asset").IsValid()
    humanoid = stage.GetPrimAtPath("/Asset/rig/Humanoid")
    # The valid bone maps; the out-of-range one is dropped. spine is a builtin of
    # the applied VrmHumanoidAPI, so the attribute always exists — "dropped" now
    # means it carries no authored value rather than being an invalid attribute.
    assert humanoid.GetAttribute("vrm:humanBones:hips").Get() == "hips"
    assert not humanoid.GetAttribute("vrm:humanBones:spine").HasAuthoredValue(), \
        "out-of-range humanoid bone should be skipped (no authored value)"
    # The raw block is still preserved even though parts were unusable.
    assert stage.GetDefaultPrim().GetCustomData().get("vrm", {}).get("rawExtension")
    # Diagnostic report: the dropped out-of-range bone is surfaced on /Asset.
    warnings = stage.GetDefaultPrim().GetCustomData().get("vrm", {}).get("warnings")
    assert warnings and any("spine" in w and "skipped" in w for w in warnings), warnings


def main() -> int:
    plugin_path = os.environ.get("PXR_PLUGINPATH_NAME")
    if plugin_path:
        Plug.Registry().RegisterPlugins(plugin_path.split(os.pathsep))
    assert Sdf.FileFormat.FindByExtension("vrm"), \
        "usdVrm SdfFileFormat is not registered"

    for check in (check_minimal, check_vrm0, check_multiskin_ibm,
                  check_unordered_skel, check_expressions,
                  check_vrm0_expressions, check_vrm0_frontbake,
                  check_textures, check_portable_package, check_animation,
                  check_lookat, check_springbone, check_names, check_materials,
                  check_constraints, check_shared_accessor, check_badext):
        check()
        print(f"  {check.__name__}: OK")
    print("usdVrm smoke tests: OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
